### ISSUE TITLE
Z Index Conflict with Navigation Subnav Menu & Stick Groups

### ISSUE THREAD

**Issue by vinnysgreen** [OllieWP/ollie#101]
**Describe the bug**
When using a subnav menu in close proximity to a sticky group in column, the subnav menu appears underneath the sticky group.

**To Reproduce**
1. Add a navigation with a subnav menu 
2. Set a group inside a column to be sticky
3. Trigger the subnav menu
4. See the subnav appear under the sticky group

**Expected behavior**
Subnav menu should always appear at the top.

**Screenshots**
![Screenshot 2023-10-22 at 9 13 05 AM](https://github.com/OllieWP/ollie/assets/13545515/10b0d572-3efd-4dee-844c-f39f1693ad40)

**Desktop (please complete the following information):**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

**Additional context**

**Comment by mikemcalister** [comment]
Good spotting, Vinny! I'll get a fix in there for this shortly!

**Comment by brdobrdo** [comment]
Maybe similar issue. Menu on mobile that expands from sticky header (header in a group that is sticky) ends up behind content below this sticky group. 
![Screenshot_20240513_232247](https://github.com/OllieWP/ollie/assets/64033592/76d853f8-2d57-4548-bbb2-26a5d9b65d9d)

**Comment by mikemcalister** [comment]
This should be fixed in the latest versions of the theme. Thanks for the heads up!
