### ISSUE TITLE
Search box responsive?

### ISSUE THREAD

**Issue by leonuts** [OllieWP/ollie#102]
Hi Mike, I love Ollie and giving it a try to replace Neve theme. However, I tried to put search box on the header, it all looks good on desktop layout, but when I open the site from mobile, it's still search with box. Is there a way to setup responsive so there's search box on desktop layout and only search icon on mobile layout (and expand when clicked)?

Thanks.

**Comment by mikemcalister** [comment]
Hi there, 

Right now, I don't think there's a way to do that with the core search box. Perhaps that's an improvement we can provide from the theme or our helper plugin. The mobile navs/header that core provides leaves a lot to be desired!

**Comment by leonuts** [comment]
I agree, everything looks nice on desktop but unfortunately some of the features are still lacking on mobile. Sadly, my 90% visitor traffic are from mobile device
