### ISSUE TITLE
Can't disable link text-decoration underline using theme style editor

### ISSUE THREAD

**Issue by mikejcoop** [OllieWP/ollie#104]
**Describe the bug**
I want to disable the default behaviour of all links being underlined in a non hover/active state. To do this I have tried going to the site editor > styles > links and setting decoration to none. 

However, the Ollie theme style.css stylesheet has text-decoration: underline set the theme uses this instead.

**To Reproduce**
1. Go to Site Editor > Styles > Links
2. Set text decoration to none
3. View any page with a link
4. See links with underline

**Expected behavior**
I should be able to use the style from the site editor. See screenshot below, where you can see the site editor style being overridden by the theme style.css rule.

**Screenshots**
<img width="200" alt="image" src="https://github.com/OllieWP/ollie/assets/73822068/a7f7613e-cb9f-4ea6-ae91-156aa3b6666b">

**Additional context**
I'm very new to the Site Editor experience, so please let me know if I have missed something.

**Comment by mikemcalister** [comment]
Hi Mike, 

Thanks for the heads up! I'll take a closer look at this and see if we can do this via theme.json now. I've just gone on a parental leave break, so it may just be a week or two before I can look at this closer. Stay tuned!

**Comment by mikemcalister** [comment]
This has been fixed and will be released in the next update.
