### ISSUE TITLE
Error installing the fonts.

### ISSUE THREAD

**Issue by Shanti9** [OllieWP/ollie#105]
I get error "Error installing the fonts." when trying to add new font in Managing fonts under Styles in both Upload or Install Fonts (Google). I'm trying this by editing Default style.

I'm using Ollie Dash 1.0 on Ollie (Version: 1.1.0) on WP 6.3.2 (with Firefox 118). All my WP folders are writable.

What could be the problem?

<img width="678" alt="Screenshot 2023-11-04 at 08 07 46" src="https://github.com/OllieWP/ollie/assets/12979646/5019f3c9-597c-4936-bef4-523b9def3d3a">

**Comment by Angelos1612** [comment]
I have the same problem and all my font suddenly disapear

**Comment by mikemcalister** [comment]
This should be fixed with the latest versions of WordPress. This isn't an Ollie specific problem, likely one with the early version of the font manager.
