### ISSUE TITLE
Installation of Ollie Dash failed

### ISSUE THREAD

**Issue by margonfil** [OllieWP/ollie#106]
**Describe the bug**
When installing both ollie-dash and also ollie-dash-main (from Git) it didn't succeed
**To Reproduce**
1. Go to 'Appearance>themes>add new'
2. Click on 'install'
3. See error: The package could not be installed. The theme does not have a style.css stylesheet.

**Expected behavior**
The theme should be installed and work without problems

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS:WINDOWS 11 (updated)
 - Chrome (last version)

**Comment by nicolasmesser** [comment]
Olli Dash is NOT  a WP theme but the companion plugin for the onboarding wizard that was initially part of the Olli theme. You need to add it as a new plugin and then follow the instructions in the readme to start the wizard.

**Comment by margonfil** [comment]
Thank you for the answer!

Mario Gonçalves

Em dom., 5 de nov. de 2023 07:57, Nicolas Messer ***@***.***>
escreveu:

**Comment by margonfil** [comment]
Everything worked fine this time. Thank you.

Why Ollie does not ask to install the plugin? I believe it would be useful.

Mario Gonçalves

Em dom., 5 de nov. de 2023 07:57, Nicolas Messer ***@***.***>
escreveu:

**Comment by nicolasmesser** [comment]
Glad to hear! The onboarding was part of the theme while it was only available through GitHub. There was some "controversy" during the process to get it in the WP theme directory - the decision to separate the onboarding wizard from the "core" theme was the result and thus things may not quite be "working" 100% at all times.

**Comment by mikemcalister** [comment]
Thanks for your help answering this, @nicolasmesser! When the plugin goes live on .org, we'll have a more direct way of installing it via a notice.
