### ISSUE TITLE
Cannot replace Header & Footer Template Parts with another from the pool of similar template parts provided in the theme

### ISSUE THREAD

**Issue by douginwimb** [OllieWP/ollie#107]
Hi, I have recently started using the Ollie theme having uninstalled the Exmoor theme (by Automattic). I have watched all the "how to" videos from the Youtube channel to get familiar with the nuts and bolts of working with the theme. However I cannot seem to be able to change the default Header or Footer template part with another more suited to my website. According to the help resources you should see a purple diamond against the block and then a "Replace" option when you click on the 3 dots. In my case, though the block is not shown as a diamond and there is no "Replace" option, only a "detach block" option.

My initial thought was that something had got corrupted so I uninstalled the theme and then reinstalled it, but with the same outcome. I also noticed that the uninstall had not removed everything as my previous customisations were still there after the reinstall - presumably you have to delete records from the MYSQL Dbse to clear out everything?

I'm using a WIN 10 Dell machine accessing Wordpress using CHROME

Any ideas what's happening and suggestions as to how to sort the problem out?

Thanks very much, Doug. I've attached screen grabs.
[Ollie Template Part Header Screens.pdf](https://github.com/OllieWP/ollie/files/13300079/Ollie.Template.Part.Header.Screens.pdf)

**Comment by mikemcalister** [comment]
Hi Doug, apologies for the confusion around this. Really, this boils down to an inconsistency in the UX around the Replace feature. You can only use that Replace option when modifying templates it seems. 

If you want to change the header/footer design on all pages at once, you need to modify the pattern template part. [I've created a video](https://share.cleanshot.com/BFSccNN3) showing how to do that. Basically, you go into the Header template part, remove the blocks that are in there, and insert a new pattern. 

Try that out and let me know how it works for you!

**Comment by tibesararchives** [comment]
The key here is to remove all the old template parts before adding one of the ollie template parts. Took me hours to figure this out - FSE is not intuitive!
