### ISSUE TITLE
Image captions on feautred images

### ISSUE THREAD

**Issue by ConvertixBe** [OllieWP/ollie#110]
When adding an image in WordPress, you always have the option of adding a caption to the image. It inserts it neatly everywhere (on blog pages & normal pages) except for features images, it never appears. For example, I can't put the photographer's copyright with it. Can this be added?

**Comment by mikemcalister** [comment]
Hi there, 

Captions aren't supported by default on featured images. You would need a plugin to activate them. You might want to check out [a plugin like this](https://wordpress.org/plugins/fsm-custom-featured-image-caption/) to get started.
