### ISSUE TITLE
How to make the header sticky for over 1024px width screens?

### ISSUE THREAD

**Issue by DesiLogi** [OllieWP/ollie#111]
Hi,
Really love the Ollie template. Is there a way to make the header sticky? Preferrably for over 1024px width? I set it to 'sticky' in the Edit Site section but it's not working. Maybe some custom css for the header class? 

Thanks for any help--
Kevin

**Comment by mikemcalister** [comment]
Hi there, check out this post for more details of how the sticky header works. https://github.com/OllieWP/ollie/issues/45

It's been answered a few times so try a search on the issues for more help! 

In your case, you'll probably need a little extra CSS to only show it at certain sizes.

**Comment by DesiLogi** [comment]
Hi Mike--thanks for the link--I've had trouble finding all the help threads. 

The other article does show how to fix the issue, which is great. However,  as soon as I changed the header settings as per the video, they only work on the Home page now. I can't figure out how to make them work on the rest of the pages.  Something got really screwed up--the text and background colors got scrambled on the header and even the page blocks. The site was really neat but now it's partially illegible. (http://staging.designerlogic.com/)... 

I realize this isn't a design flaw on the part of Ollie (it's a great template) but sometimes when you change one thing there's a cascade effect that's not very clear at all--maybe a WP thing.. 

Thanks for the help, hopefully I'll get it figured out. 

Best,
Kevin

**Comment by DesiLogi** [comment]
I got it worked out--thanks for the link before. Just looking for a mega-submenu type option, will browse your threads here.
