### ISSUE TITLE
Link text - additional decoration for link states

### ISSUE THREAD

**Issue by MacDGraham** [OllieWP/ollie#112]
![image](https://github.com/OllieWP/ollie/assets/99348488/d9310194-14e3-4109-badb-3bf3bcad174d)

**Is your feature request related to a problem? Please describe.**

I would like to be able add a hover state to text.

**Describe the solution you'd like**
Ability to manage a HOVER state, for:
- Font
- Style (size, apperance, etc.)
- Underline
- Colour

**Describe alternatives you've considered**
I have thought about adding Custom CSS, but have opted against it as I don't want to hack settings and would rather manage them through the UI.

**Additional context**

**Comment by mikemcalister** [comment]
Hi there, currently the UI does not support the hover styles, but it looks like this should be coming to the next update to WordPress. Once that is released, we will support it!
