### ISSUE TITLE
Sticky header not working

### ISSUE THREAD

**Issue by ischnee** [OllieWP/ollie#113]
**Describe the bug**
Using FSE I edited the header and chose position "sticky". But when I visit the site, the header scrolls and is not sticky. The div class in the header has "is-position-sticky", but it still scrolls and doesn't stick. 

**To Reproduce**
1. Go to: my website: https://ianschnee.com/
2. Click on: the header with inspector. 
3. Scroll down to div in the header.
4. See: class "is-position-sticky"

**Expected behavior**
Expected header to be sticky, but it scrolls. 

**Desktop (please complete the following information):**
 - OS: iOS Ventura 13.6
 - Browser: Verified same behavior on Firefox and Chrome. 
 - Version: Firefox 119.

**Additional context**
Thank you!

**Comment by mikemcalister** [comment]
Hi there, 

This question has been answered a few times. Check out this thread for an example of how to make it work. https://github.com/OllieWP/ollie/issues/19
