### ISSUE TITLE
Ability to hide Featured Image on post

### ISSUE THREAD

**Issue by MacDGraham** [OllieWP/ollie#114]
**Is your feature request related to a problem? Please describe.**
I add featured images to posts for index lists, SEO... but I don't always want them to appear on the post pages. 

**Describe the solution you'd like**
I'd like the option to be able to select if I want the featured image to appear on the post page via a check box. I've seen this functionality on other themes and found it really useful.

[  ] Display featured image on post page

**Describe alternatives you've considered**
I am not sure what alternatives exist.

**Additional context**

Current state:
![Screenshot 2023-11-27 150855](https://github.com/OllieWP/ollie/assets/99348488/fb392225-3271-414f-8360-6a2de0e6744c)

Future state:
![ollie-featured image](https://github.com/OllieWP/ollie/assets/99348488/205319c1-7ee8-4243-b36f-331188e433f1)

**Comment by mikemcalister** [comment]
Hi there, you could install a plugin [like this one](https://wordpress.org/plugins/conditionally-display-featured-image-on-singular-pages/) to add that functionality. Hope that helps!

**Comment by MacDGraham** [comment]
It's perfect :)
