### ISSUE TITLE
Vertical Text Alignment

### ISSUE THREAD

**Issue by Inn8ly** [OllieWP/ollie#116]
A vertical text alignment setting was introduced recently. WP 6.4, I think. We need it for a design, but the setting isn't unavailable when using Ollie. I switched to 2024, and there it was. https://ai-color-spectra.instawp.xyz/ We don't like to bounce around different themes to be consistent and simplify training. One of our developers can manage this with CSS. Let us know if this setting will be available in a future Ollie update.

**Comment by mikemcalister** [comment]
I've noted this as a feature to add in the upcoming versions of the theme. Thanks for the suggestion!
