### ISSUE TITLE
"Site Logo" block doesn't stop loading with WP 6.4.1

### ISSUE THREAD

**Issue by dylan-wu** [OllieWP/ollie#117]
**Describe the bug**
I'm not sure this is an issue with Ollie, still a WP noob so may be my own confusion, but just in case: Upon adding a "site logo" block into the site, it displays an unclickable spinner icon forever, rather than an upload icon.

**To Reproduce**
1. Go to theme editor
2. Edit header template
3. Add a "site logo" block

**Expected behavior**
Upon adding "site logo" block, should immediately transform to an upload button, allowing you to upload media.

**Screenshots**
![Animation](https://github.com/OllieWP/ollie/assets/6586811/6363c662-ac48-43a6-a3a7-be21a675f96c)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - WP 6.4.1
 - Ollie 1.1.0

**Comment by mikemcalister** [comment]
This appears to be a WordPress problem, not specific to Ollie. I'm going to close this as its likely resolved at this point, but please reopen if you think it is related to the theme.
