### ISSUE TITLE
Navigation block does show sub menu links in editor and just doesn't show links and theirsubmenu links on frontend whatever i do ) :

### ISSUE THREAD

**Issue by D0skata** [OllieWP/ollie#120]
**Description**

I have WordPress 6.4.2 on php 8.0 installed and i don't see the Menus under Appearance but i get only Navigation in Design in the Editor of the theme. 

**To Reproduce**
When i create one navigation with sub menu links i do see them in the Editor, but those links then do not show up on the front end any browser. I do not know how to fix it at all. I'm a beginner with wp and all. 

**Expected behavior**
can u help me out with resource or tutorial to follow up? i hv the same problem with other themes as well...

**Screenshots**
i share the screenshot illustrating the issue ( : 
![Screenshot-2023-12-09-at-12-30-00-WordPress](https://github.com/OllieWP/ollie/assets/153357780/80d67bee-b9d5-4c43-b34b-530216e2c6dd)

**Desktop (please complete the following information):**
i see the bug on
 - windows 8.1
 - Firefox, Chrome, neither on Brave 
 - WordPress 6.4.2 on php 8.0 

**Smartphone (please complete the following information):**
neither on
 - iPhone 7
 - iOS 15.8
 - Safari 

**Additional context**
None

**Comment by mikemcalister** [comment]
Hi there, sorry for the delay, I'm just getting back from parental leave. Are you still having this issue? I cannot reproduce on my end.

**Comment by D0skata** [comment]
All is good now! Thanks for reaching out, u can delete my help request ( :
