### ISSUE TITLE
Using dropdowns on mobile navigation instead of just listing pages

### ISSUE THREAD

**Issue by maxamato120** [OllieWP/ollie#121]
Hi,

I'm creating a website that is going to have 40+ pages when it's complete, with multiple levels of subpages. With the default mobile navigation, this would be quite unsightly and hard to find what you want. 

How can I use dropdowns for subpages instead of having all of them stacked under their parents?

Thanks

**Comment by mikemcalister** [comment]
Hey there, 

Unfortunately there isn't a great way to do that with the core navigation system yet. Hopefully they'll improve that in the 6.5 release. The only way to change the behavior would be to custom code something for the menu.
