### ISSUE TITLE
Parent Page in Navigation not linked

### ISSUE THREAD

**Issue by brickkk** [OllieWP/ollie#122]
I created a page and added several other pages to be childs of that page. I arranged the navigation accordingly. Unfortunately the parent page is not a link and clicking it only reveals the sub-menu.

I would like the sub-menu to appear on hover of the parent page and the parent page also to link to the page.

**Comment by mikemcalister** [comment]
Hi there, sorry for the delay in response here. Just getting back from parental leave. 

Did you get this sorted out? If the page isn't a link, you can make it one a few different ways. But you should be able to choose the page/link from the inserter in the navigation block. Let me know, happy to advise.

**Comment by mikemcalister** [comment]
Just had a closer look at this. As you mention, you have the "Open on click" setting enabled on the navigation block (see screenshot below). If you turn this setting off, the link will be clickable and the sub menu will show on hover.

<img width="317" alt="Screenshot 2024-01-23 at 10 09 10 PM" src="https://github.com/OllieWP/ollie/assets/1415737/29980315-ecf3-4bd7-8252-ee5bd96a1906">
