### ISSUE TITLE
Up Arrow

### ISSUE THREAD

**Issue by tibesararchives** [OllieWP/ollie#123]
Hi Michael,

A lot of my blog pages are very long, and even longer on mobile.

I transitioned from the Kadence theme which had an up arrow to Ollie. Boy, I have never worked with FSE but I eventually figured it out watching your videos (FSE is NOT intuitive for sure).

Anyways, I would like an Up Arrow for both desktop and mobile please. 

Your Ollie theme is really nice.

Thank you Sir!

Marcus Tibesar

**Comment by mikemcalister** [comment]
You might try a plugin like this: https://wordpress.org/plugins/scroll-top/
