### ISSUE TITLE
Main Blog Archive page - heads in photos being cut off

### ISSUE THREAD

**Issue by tibesararchives** [OllieWP/ollie#124]
Howdy Michael,

Reference:  https://www.tibesar.family/category/news/

Hey Michael,

Some of the heads of people are cut off in the blog posts listed on the main Blog archive page. Referenced page refers.

Is this a css issue with the Ollie theme?

Thank you,

Marcus Tibesar

**Comment by mikemcalister** [comment]
If you want the images to be shown with their original height, you can remove the height restriction on the blog index template. 

<img width="323" alt="Screenshot 2024-01-23 at 9 39 24 PM" src="https://github.com/OllieWP/ollie/assets/1415737/4719c100-285b-4d83-958b-e8f000f543d8">
