### ISSUE TITLE
Server PHP error

### ISSUE THREAD

**Issue by tibesararchives** [OllieWP/ollie#125]
I a seeing the following PHP errors which are hard for me to decipher the source (theme or plugin) of the error. Are these Ollie Theme errors please?

Website Error Log:

[Tue Jan 02 19:43:30.862335 2024] [autoindex:error] [pid 3564308:tid 140486962489088] [host www.tibesar.family] [client 91.134.248.253:43828] AH01276: Cannot serve directory /var/www/html/ti/tibesar.family/wp-admin/css/colors/: No matching DirectoryIndex (index.html,index.htm,index.shtml,index.php,index.php5,index.php4,index.php3,index.cgi,default.html,default.htm,home.html,home.htm,Index.html,Index.htm,Index.shtml,Index.php,Index.cgi,Default.html,Default.htm,Home.html,Home.htm,placeholder.html) found, and server-generated directory index forbidden by Options directive, referer: http://tibesar.family/wp-admin/css/colors/index.php

[Tue Jan 02 17:17:01.956834 2024] [autoindex:error] [pid 3509681:tid 140486836598528] [host www.tibesar.family] [client 20.163.13.149:63937] AH01276: Cannot serve directory /var/www/html/ti/tibesar.family/wp-admin/css/colors/coffee/: No matching DirectoryIndex (index.html,index.htm,index.shtml,index.php,index.php5,index.php4,index.php3,index.cgi,default.html,default.htm,home.html,home.htm,Index.html,Index.htm,Index.shtml,Index.php,Index.cgi,Default.html,Default.htm,Home.html,Home.htm,placeholder.html) found, and server-generated directory index forbidden by Options directive, referer: http://tibesar.family//wp-admin/css/colors/coffee/index.php

[Tue Jan 02 04:27:49.972313 2024] [autoindex:error] [pid 2876025:tid 140487012841216] [host www.tibesar.family] [client 45.141.215.120:58605] AH01276: Cannot serve directory /var/www/html/ti/tibesar.family/wp-includes/js/tinymce/plugins/compat3x/css/: No matching DirectoryIndex (index.html,index.htm,index.shtml,index.php,index.php5,index.php4,index.php3,index.cgi,default.html,default.htm,home.html,home.htm,Index.html,Index.htm,Index.shtml,Index.php,Index.cgi,Default.html,Default.htm,Home.html,Home.htm,placeholder.html) found, and server-generated directory index forbidden by Options directive, referer: http://www.tibesar.family//wp-includes/js/tinymce/plugins/compat3x/css/index.php

**Additional context**
I am running the Ollie Theme Version: 1.1.0

**Comment by mikemcalister** [comment]
This does not seem to be theme related. I don't see any errors relating to the theme folder. Looks like it's related to your admin color scheme, so check any plugins that may be modifying that.
