### ISSUE TITLE
How to install Google Analytics tag

### ISSUE THREAD

**Issue by mbelmar05** [OllieWP/ollie#126]
Hi guys.
I am trying to figure out where to paste my Google Analytics tag in the header of the Ollie Theme.
I am just unable to find the place. Maybe there is another way?
Thank you very much in advance.

**Comment by Inn8ly** [comment]
Some years ago, we developed Tracking Scripts Manager, a plugin that facilitates adding all sorts of tracking scripts including the GA tag. https://wordpress.org/plugins/tracking-script-manager/

**Comment by mikemcalister** [comment]
Hi there, I would look at a plugin to do that. Something like this could work: https://wordpress.org/plugins/header-footer/

**Comment by mbelmar05** [comment]
Thank you very much. I ended up installing google site kit
