### ISSUE TITLE
Make the Archives Pages the same as the Pages

### ISSUE THREAD

**Issue by tibesararchives** [OllieWP/ollie#127]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tibesararchives** [comment]
The header of the Archives (title; placement of the title; font size) are so different than the regular Pages. It seems theme developers always overlook this detail.

Please make the default main Archives Pages be consistent with the default Pages. 

And, yes we modified our Archives Pages to match the header layouts within the Pages.

Thank you for a well designed Ollie block theme. We really like your attention to details Michael!

**Comment by mikemcalister** [comment]
Sorry, but this is a stylistic choice I've made on this one. Glad you figured out how to modify it on your site though.
