### ISSUE TITLE
Pagination - need Blog post numbers

### ISSUE THREAD

**Issue by tibesararchives** [OllieWP/ollie#130]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tibesararchives** [comment]
Hello,

My website has over 1,000 blog posts. Ollie's pagination when advancing through the Blog is PREVIOUS & NEXT

I really need pagination that advances by numbers (i.e. 100, 200, 300, etc.)

Can this be added to Ollie?

Thank you,

Marcus

**Comment by mikemcalister** [comment]
Add the pagination numbers by editing the template, clicking the [+] button in the middle of the block and adding Page Numbers. 

<img width="1094" alt="Screenshot 2024-01-23 at 9 33 09 PM" src="https://github.com/OllieWP/ollie/assets/1415737/95da0c5b-10e3-47f9-ae4b-69fce108d023">
