### ISSUE TITLE
Add "Read More" Link Text 

### ISSUE THREAD

**Issue by tibesararchives** [OllieWP/ollie#132]
**Describe the bug**
I cannot find the location where to add the "Read More" link text on the Index and All Archives templates.

**To Reproduce**
1. Go to Editor
2. Go to Templates
3. Go to Index or All Archives template
4. Click on the Pencil Edit 
5. Drill down to the Excerpt block within the Query Loop
6. No where to update or add the Read More link text

**Expected behavior**
I was not able to modify or add  the Read More Link Text on the Index and All Archives templates 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Sonoma 14.2.1
 - Browser Safari
 - Version 17.2.1
<img width="1457" alt="Screenshot 2024-01-14 at 8 10 07 PM" src="https://github.com/OllieWP/ollie/assets/101951477/0fe193b4-ea24-4a87-8436-5c78c11711b6">

**Additional context**

**Comment by mikemcalister** [comment]
In your screenshot, below the excerpt, there is text that says **Add "read more" link text**. That's where it goes.
