### ISSUE TITLE
Tags line on mobile does not wrap

### ISSUE THREAD

**Issue by tibesararchives** [OllieWP/ollie#133]
**Describe the bug**
On mobile posts with a lot of tags. When viewing a post with several tags; the tags don’t wrap and run off the right side of the mobile view 

**To Reproduce**

**Expected behavior**
Poss with many tags; tag line should wrap

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mikemcalister** [comment]
Fixed in upcoming version v1.1.1.
