### ISSUE TITLE
Wordpress Editor Formatting

### ISSUE THREAD

**Issue by KYM2404** [OllieWP/ollie#135]
Hi, 

Downloaded Ollie WP, love it for the most part. But the content editor – where you edit and write posts – is all messed up. The formatting is all over the place, there's no correct spacing between elements – a H2 tag and <p> tag and it is making editing and uploading content next to impossible. 

Appreciate I could be missing an obvious feature or setting here, but I'm pretty new to block editors. Can you assist?

**Comment by mikemcalister** [comment]
Hey there, can you send a screenshot of what you're seeing. This is unlikely the theme itself. It could be that old content from an old theme isn't displaying optimally though. Show me what your'e seeing!

**Comment by KYM2404** [comment]
Hey Mike, Sorry for the late response. I’ve sorted it now. One thing I can’t seem to get working though is the child theme. Every time I activate it, it doesn’t bring over all the settings from main theme — it reverts back to Ollie Theme layout in the footer. Any idea how to fix this? CheersRichard Sent from my iPhoneOn 23 Jan 2024, at 21:29, Mike McAlister ***@***.***> wrote:﻿
Hey there, can you send a screenshot of what you're seeing. This is unlikely the theme itself. It could be that old content from an old theme isn't displaying optimally though. Show me what your'e seeing!

**Comment by mikemcalister** [comment]
This is expected behavior, although it's not obvious or intuitive. The settings and edits you make to your theme via the UI are tied to the theme name. So when you switch from Ollie to Ollie child theme, WordPress looks at that as a different theme. 

You might want to check out the [Create Block Theme plugin](https://wordpress.org/plugins/create-block-theme/), which has a few different tools to help you export your changes to a theme or child theme.

**Comment by KYM2404** [comment]
Hey,Cheers for the replay, I see Ollie Pro has launched. What’s the deal with switching to it? Does it work with standard and just overlay? CheersRSent from my iPhoneOn 10 Jul 2024, at 20:18, Mike McAlister ***@***.***> wrote:﻿
This is expected behavior, although it's not obvious or intuitive. The settings and edits you make to your theme via the UI are tied to the theme name. So when you switch from Ollie to Ollie child theme, WordPress looks at that as a different theme.
You might want to check out the Create Block Theme plugin, which has a few different tools to help you export your changes to a theme or child theme.

**Comment by mikemcalister** [comment]
@KYM2404 Ollie Pro uses the same Ollie theme that you already have installed! So you don't need to switch anything over, you just need to update to the latest version of Ollie. 

Ollie Peo adds a pattern library to your site with hundreds of patterns and full page layouts to choose from. All of these patterns can be mixed and matched, giving you tons of layout options. 

In the future, there will also be some Pro blocks released.
