### ISSUE TITLE
Mobile menu

### ISSUE THREAD

**Issue by baeredigital** [OllieWP/ollie#141]
Hi

I am testing out ollie, and find a lot very nice. But it is one thing that I really would like to change. 

When you choose de mobile menu, on a desktop, it fill the whole screen. I would very much like the with to be thighter, mnaybe i fixed with.  

Here is an example.  https://kistefos.no/

Is this possible? If not can you put in on your feature list?

Thank you in advance,
Bjorn Stig, Olliefan :-)

**Comment by mikemcalister** [comment]
Hi there, 

Right now the mobile menu is quite limited with block themes, unfortunately. However, we're exploring ways to have a much better mobile menu experience and when we do, it will be available in the Ollie theme!

**Comment by DecimusBurton** [comment]
That's fantastic news - mobile menu in current FSE is pretty basic and not very user friendly at the moment - as there is no collapse.  

According to Kathryn Presner (@zoonini) a WordPress moderator "the Navigation block is designed to expand all submenu items in the mobile version, and there isn’t a built-in way to change that behaviour"  REALLY! 
see: https://wordpress.org/support/topic/collapse-sub-menu-on-mobile/

We have just transitioned our site to Ollie: https://www.bajanthings.com/

For mobile having collapsed submenus was a built in feature of Astra Pro which our site was previously built with!

The biggest negative feedback on the move to Ollie has been the fully expanded and ungainly mobile menu.

I note that @pareshsojitra commented on Jan 29 in this link: https://github.com/WordPress/gutenberg/issues/38599
