### ISSUE TITLE
Image compression

### ISSUE THREAD

**Issue by vastzor** [OllieWP/ollie#142]
Switched from blocksy to the ollie theme - noticed content compression with the ollie theme, all images for instance experienced a size reduction of at least 50%. Is there anyway I can automatically resize all content without having to resize each item one at a time?

**Comment by mikemcalister** [comment]
Hi there, 

Where are you seeing the image size issue? I don't know how Blocksy handles images, but Ollie just uses the core image block and the sizes included with it. So we don't resize images, but you may need to select the right size in the image block's settings.

**Comment by vastzor** [comment]
In Blocksy I selected the row which contains one of the images to make a note on image dimensions “custom content max width” is set at 1200 px and the image runs from one side of the desktop screen to the other which is the way it is suppose to be. When I switch to the Ollie theme same settings as above however the image is compressed. If seem like there is right and left universal padding for the entire homepage which is causing the compression of all the images and fonts. 

Awesome theme and support though. It is something I would actually pay for.
![Blocksy theme](https://github.com/OllieWP/ollie/assets/162372554/00e87762-51d0-4ca9-af07-56c7d40307c7)
![Ollie theme](https://github.com/OllieWP/ollie/assets/162372554/d3020f96-3a30-4a35-aa9a-0685f84be789)

**Comment by vastzor** [comment]
I watched your videos to try to understand why the content on the page is
not appearing in full width. I went to page settings and changed the
template from the default page template to page no title full width saved
and viewed the page  and content does not appear full width. I do not know
why this is happening. I then just created a new page and inserted a full
width image, changed page settings to template full width with no title and
again the image will not appear in full width after the page was saved and
viewed. The only time I can get content to appear full width is if I
publish a pattern as you demonstrated in your video. Anyway kind of counter
intuitive hope you can help otherwise no worries

**Comment by mikemcalister** [comment]
Did you also make sure to set the width on the image using the alignment option? 

<img width="1171" alt="Screenshot 2024-03-07 at 1 32 40 PM" src="https://github.com/OllieWP/ollie/assets/1415737/b592939a-b9d9-403d-817f-b11450a408e3">

**Comment by vastzor** [comment]
Switched from the default template to the no title full width template-
that took care of it. Thanks

**Comment by vastzor** [comment]
Sorry what I meant to say is that I changed global layout setting to 1260 x
1260
