### ISSUE TITLE
What are benefits of using OllieWP and SimplyStatic? together?

### ISSUE THREAD

**Issue by e-orlov** [OllieWP/ollie#143]
OllieWP is a fruit of the teamwork by Mike and Patrick of SimplyStatic. So I would like to know, are there any special (technical) benefits of using OllieWP and SimplyStatic together?

**Comment by mikemcalister** [comment]
Hey there, the obvious benefit is just the performance enhancements you get with any static site. Ollie is a block theme, which means it does some tree shaking of styles automatically. But an entirely static version of it could give you an even faster site on the front end, with all the powerful design tools on the backend.

**Comment by mikemcalister** [comment]
I should also mention, Patrick's Simply Static plugin is on sale right now for a limited time! You can [find it here](https://appsumo.com/products/simply-static/).

**Comment by e-orlov** [comment]
> I should also mention, Patrick's Simply Static plugin is on sale right now for a limited time! You can [find it here](https://appsumo.com/products/simply-static/).

This is interesting. How correlate these offers with the start and pricing of Central?
