### ISSUE TITLE
::placeholder effecting WP UI

### ISSUE THREAD

**Issue by kauaicreative** [OllieWP/ollie#145]
**Describe the bug**
::placeholder {
	color: var(--wp--preset--color--secondary);
	font-size: var(--wp--preset--font-size--small);
	opacity: 0.75;
}
is effecting WP UI

**To Reproduce**
1. Insert an image
2. Select the image
3. Insect width height
<img width="606" alt="image" src="https://github.com/OllieWP/ollie/assets/127033/eb58c048-ffc1-4e3d-b7d4-5ba7f8e7e38d">

**Expected behavior**
<img width="606" alt="image" src="https://github.com/OllieWP/ollie/assets/127033/a0a3240c-8d9e-41ac-9c57-45690f30ad6e">

**Screenshots**

**Desktop (please complete the following information):**
 - iOS
 - Brave
 - Latest

**Comment by mikemcalister** [comment]
This appears to be fixed by WordPress core now. Looks like it was a scoping issue.
