### ISSUE TITLE
bug in "Expand on click" in the new wordpress update

### ISSUE THREAD

**Issue by osintguardian** [OllieWP/ollie#146]
1 hour ago I updated WordPress to version 6.5 and everything was going well until I realized that the "Expand on Click" function did not work in Firefox-based browsers

All Firefox based browsers seem to have bugs with the ability to enlarge images with websites using this theme.

how the error occurs:
1: enable the "Expand on click" function on an image in a post or page
2: publish the posts on the website (private / public or with password)
3: go to the posts uploaded on the website in a firefox based browser or just firefox
4: click on the image to enlarge it

Expected behavior:
I use Firefox and another browser based on Firefox, I expected after updating WordPress to continue editing an article and when I went to enlarge the image I realized that this WordPress function did not work.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox and Mullvad Browser
 - Version: 124.03 (64-bit)

**Additional context**
A few minutes after realizing the error and analyzing it, I ran WordPress with the Ollie theme on a domain for testing and apparently the error was still active but sometimes the enlarge image function worked well. For example, in normal Firefox it worked but in Mullvad Browser (browser based on Firefox) it did not work yet.

This error started when I installed the latest version of WordPress, in the previous version of WordPress everything works fine, when I saw this I ran the test website with another theme and the error disappeared.

Greetings and thanks for reading

**Comment by mikemcalister** [comment]
Hi there,

Thanks for the report, but I'm not seeing the same issue in WP 6.5. The expand on click works for me in all browsers, including in Firefox. I also tested the TwentyTwentyFour theme just to be sure, works there too. 

If this was broken though, it would be a core issue, so hopefully they'd fix that up. We don't have anything in the theme that would break that functionality. I'll keep an eye out to see if anyone else reports it.
