### ISSUE TITLE
Barbara Funaro Psicologa Psicoterapeuta Milano

### ISSUE THREAD

**Issue by jilloau** [OllieWP/ollie#148]
Hello

I used the wizard but my content  has not propogated and and homepage is missing??  The blog content is there!
Can you help.

Thanks

![ollie setup wizard homepage](https://github.com/OllieWP/ollie/assets/166347902/70d4cf34-964a-4bd4-9195-fe9dcb994497)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mikemcalister** [comment]
This issue should be fixed now. The site wizard was recently moved to Ollie Pro, so this isn't available as a standalone plugin anymore.
