### ISSUE TITLE
Child theme and woocommerce

### ISSUE THREAD

**Issue by elito** [OllieWP/ollie#150]
**Describe the bug**
When using a child theme on woocommerce shop page website header is not displayed

**To Reproduce**
1. Install and activate ollie child theme
2. Install woocommerce
3. Got to de shop page 
4. Header is not here

**Comment by mikemcalister** [comment]
Hi there, 

Sorry for the late response here. I'm not super familiar with WooCommerce at this point and how it works with block themes and template parts. In the future, Ollie may be optimized for WooCommerce, but right now, we're not focused on optimizing it for ecommerce.
