### ISSUE TITLE
Scroll to top icon added in Pro

### ISSUE THREAD

**Issue by DecimusBurton** [OllieWP/ollie#153]
**Is your feature request related to a problem? Please describe.**
I miss the built in scroll to top that was present in Astra Pro

**Describe the solution you'd like**
I've tried a number of plug in options but none seem satisfactory.

**Describe alternatives you've considered**
I've implemented a php snippet using code from here:
https://redpishi.com/wordpress-tutorials/back-to-top-button-wordpress-without-plugin/

**Additional context**
I am seeing an issue with the scroll-to-top.  It might be being cached so its only appearing on some pages.  Often if I link from the home page say from a current post then second time around I don't get a scroll to top icon!
home page: https://www.bajanthings.com/

Really looking forward to Ollie Pro launching

**Comment by mikemcalister** [comment]
Hey Peter, 

I don't think we'll be doing a scroll to top option in the theme at this time. Something to consider for down the road though! 

I can't see it on your site now. I would maybe implement that as a global element, maybe in the Page template above the content area as a sticky item.

**Comment by DecimusBurton** [comment]
Its there

[image: image.png]

Its via a snippet but I needed to turn off AdSense Anchor ads ;-)

That's not a big issue as they don't really generate much revenue!  Scroll
to top via

https://redpishi.com/wordpress-tutorials/back-to-top-button-wordpress-without-plugin/


---
Peter Burton 巴培德
email: ***@***.***
UK mobile: 0787 261-0026

-
Peter this November is supporting Movember for the 13th year
https://movember.com/m/decimus?mc=40
-
skype: decimus_burton
-
UK address:  Silver Trees, Warren Drive, Kingswood, Surrey, KT20 6PT, UK.
-
Email Disclaimer: The information in this email is confidential and may be
legally privileged. It is intended solely for the addressee.
