### ISSUE TITLE
Login/ registration form or page

### ISSUE THREAD

**Issue by DjWellz** [OllieWP/ollie#155]
Hello. thanks for the Ollie theme. I'm using it on my website which was originally built with WordPress Genesis theme and a child theme named Darling from Restored316. I'm not a web designer nor a coder, so it took some time for me to learn all I needed in order to make the switch and redesign the site without breaking it. The site www.tejedastots.com is an educational blog and also has a WooCommerce shop. One of my goals in making the switch to Ollie was to minimize the number of plugins and widgets needed to run the site while giving it fresh new look. I've managed to get rid of a bunch of plugins, but I have a question about one that I'm unclear about named RegistrationMagic. From what I can see, the only RegistrationMagic function being used on the site is a Login form. I don't know how it was being used before, but I do see that there is a short code labelled [Login_Form] that is part of plugin. On my website there is a My Account link on the navigation bar, which when clicked, opens to a page where the user can either login or register. Originally, I thought that the Login form made by Registration magic was creating this page/form, but after deactivating the plugin, I still see the same Login and Registration section. Does Ollie and WordPress 6.5.2 include this form natively? If so, it seems like I can delete the RegistrationMagic plugin since I don't see any other form or place where it might be in use.

**Comment by mikemcalister** [comment]
Hey there, sorry for the delay here. 

WordPress only ships with a login/logout link block. You can see if you search your blocks for `login`. This link will redirect users to the standard WordPress login page.
