### ISSUE TITLE
Ollie Theme questions

### ISSUE THREAD

**Issue by PrompticAI** [OllieWP/ollie#159]
Dear Ollie Team, 

I tested the Ollie WP theme to see if it would suit my project for the blog website I'm building. So far, I have to say it's a very nice and clean theme without too many bells and whistles. 

I just started, and I'm in the setup/design phase to see if I can finish my website vision. On your website, olliewp.com, I saw that the header menu has a Hoover function with a line under the words. I did not find this somewhere in the settings; I might have overlooked it. Can you please tell me if it is a setting or custom-made? 

Another question I have is if it's possible to link pages in the footer without having the hyperlink line under the words. 

Best regards, 
Marcel

**Comment by mikemcalister** [comment]
Hi there, 

If you are using a navigation menu in the header, it should automatically use the underline style on hover. You'd have to send me a link so I could check it out though. 

If you wanted the same effect in the footer, you could use some custom CSS to do it. Hopefully we'll be able to do hover styles in the UI soon! 

```
footer a {
    text-decoration: none;
}
```

You shouldn't need to add the underline style for hover, the theme should do it automatically. 

To add this CSS, go into the Site Editor (Appearance -> Editor) and open the Global Styles panel, and then click the three dots to reveal the Additional CSS panel.

<img width="759" alt="Screenshot 2024-05-13 at 3 38 05 PM" src="https://github.com/OllieWP/ollie/assets/1415737/0d403c81-904e-4c09-aceb-ac491de7eac6">
