### ISSUE TITLE
Ollie Dash generated content/pages

### ISSUE THREAD

**Issue by blitzgeek** [OllieWP/ollie#161]
Hello Mike,
I used the setup-wizard to create the pages, which works fine.
But only until I change the theme.
After that, the pages created with the ollie-dash-plugin are only displayed empty in the frontend and only a "pattern placeholder" block can be seen in the editor. Screenshots are attached.
Only when I copy the automatically generated content manually with "Copy all blocks", delete the generated content and paste it again, everything works.
Environment:
Local, Server Nginx, MySQL 8.0.16, PHP 8.3.0, WP 6.5.3
OS: Mac Sonoma 14.4.1 (23E224)
Browser: Safari Version 17.4.1
Best regards
Volker (info@blitzgeek.net)
![ollie-issues-with-plugin-created-content](https://github.com/OllieWP/ollie/assets/10080048/3db89306-9e4f-4a8f-a3d8-6546c519c705)

**Comment by nicolasmesser** [comment]
Sounds like this would be expected behavior as the (example/placeholder) patterns relate to a specific theme (unless you save them in your library?). Don't think this really is an Ollie related issue since you switched to another theme.

**Comment by blitzgeek** [comment]
Not sure about that, because with the (theme-specific) patterns built content stay after a theme-change.
And the ollie-plugin helps to get started and prebuilts the pages you want. It would therefore be fatal if the website were to disappear completely just because you switch to a different theme.
