### ISSUE TITLE
Gravity forms plugin

### ISSUE THREAD

**Issue by shitenhai** [OllieWP/ollie#162]
We have created a lot of forms using Gravity forms. If we change our theme to Ollie and later use Ollie Pro, can we retain our Gravity forms plugin or better still, how to create similar forms using Ollie or Ollie Pro that can replace the need for Gravity Forms?

**Comment by slaFFik** [comment]
You won't be able to replace Gravity Forms with Ollie Pro. 
Gravity is a _forms_ plugin, Ollie is a theme, and Ollie Pro is a plugin that extends the theme.
Gravity Forms will embed itself into _any_ theme, be it Ollie or Ollie Child, or any other theme out there.
Ollie Pro is a not a site builder, like Elementor or Divi which have their own forms modules.

**Comment by mikemcalister** [comment]
Thanks for the response, @slaFFik. 

Form blocks will be coming to WordPress core eventually, and work is [already underway for them](https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BBlock%5D+Form+%28experimental%29%22). When those do launch, Ollie will support them and have all the nice styling for them. 

Until then, Ollie does not offer any kind of form solution.
