### ISSUE TITLE
Additional CSS gone missing from Ollie!

### ISSUE THREAD

**Issue by DecimusBurton** [OllieWP/ollie#163]
With the Ollie theme under Appearance | Customise there were 3 settings: Site Identity, Homepage Setting and Additional CSS. 

Under Additional CSS we pasted in a bunch of CSS to fix navigation and fine tune some other issues we had.

The site is: BajanThings.com

The Customise setting seems to have totally disappeared!

I can see Additional CSS via Global Styles but it has nothing in it.

I can also see via Appearance | Theme | Ollie that at the bottom are 3 buttons: Customise, Additional CSS and Forms.... still no sign of my Additional CSS.

All the CSS is still working as it was used to fix the navigation menu and a few other tweaks.

I have a text file of an old update listing the CSS I added.

I just cannot find where my Additional CSS has now disappeared to.  

Mike - Any hints of where I might look so I can tweak my CSS

Many thanks

Peter

**Comment by DecimusBurton** [comment]
FOUND IT .... not sure why its now hidden but with a lot of Googling I found it via:
https://www.bajanthings.com/wp-admin/customize.php

**Comment by mikemcalister** [comment]
Hey Peter, 

Just a quick heads up that they are slowly getting rid of the Customizer, so you can start using the Additional CSS field in the global styles panel.

**Comment by DecimusBurton** [comment]
all done


---
Peter Burton 巴培德
email: ***@***.***
UK mobile: 0787 261-0026

-
Peter this November is supporting Movember for the 13th year
https://movember.com/m/decimus?mc=40
-
skype: decimus_burton
-
UK address:  Silver Trees, Warren Drive, Kingswood, Surrey, KT20 6PT, UK.
-
Email Disclaimer: The information in this email is confidential and may be
legally privileged. It is intended solely for the addressee.
