### ISSUE TITLE
Changing style of links & buttons

### ISSUE THREAD

**Issue by heldenhaft1** [OllieWP/ollie#165]
The theme is really great!

I just don't understand how I can change the general design of the "links" and "buttons" in this theme.

The links are currently underlined when :hover is selected. However, I would like it to be the other way around.

For the buttons, I would like them to change color as soon as I hover the button. Currently, the button background does not change at all, only the text in the button is underlined when :hovered.

Where is the official right place to make these settings? Is it "Custom CSS" or is there another option?

Thank you and best regards

**Comment by mikemcalister** [comment]
Hey there! Apologies for the late response. 

Unfortunately, we _still_ don't have :hover styles supported in the WordPress block editor UI. However, it is planned and [in the works](https://github.com/WordPress/gutenberg/issues/38277), so hopefully in the next few releases we'll see that. Then, you'll be able to adjust those right from the interface. 

For now, you'd have to do it with good ol' fashioned CSS.
