### ISSUE TITLE
remove underscore on links

### ISSUE THREAD

**Issue by raven4thchute** [OllieWP/ollie#166]
**Describe the bug**
Not sure if this is a bug (I am just a competent amateur in terms of web knowledge) but I could not get rid of the link underline when posting a page to a live site.

Reproduce:
I wanted to get rid of the link underline. To do this, I edited the Ollie theme using the site editor (in the Styles section) and selected "decorations - none" for links. The style updated in the editor but the small example display still showed an underline. After saving the change, the links on the page shown in the site editor displayed properly and they also displayed properly when a "prevue in new tab" was selected. However, when the page was posted, the link-underline was back again (I reloaded the page, cleared the cache, tried a different browser etc.) 

I created a child-theme and added CSS to remove the underline.  Same behavior as above - the live site had underlines.

In looking at the page script of the live site it appeared that the page was still using the Ollie default script settings:
a,
a:focus,
a:hover {
	text-decoration: underline;

I edited the script in the original Ollie theme file to:
        text-decoration: none;
and everything appears to now be working .

This is not ideal since it will be overwritten with a theme update. 

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Edge
 - Version 126.0.2592.61

Thanks for your time!

**Comment by mikemcalister** [comment]
Hey there, 

Thanks for the detailed report. I've just made a few fixes to the Ollie theme that should help with this issue. I've removed the underline styling from style.css, so the editor should take precedent now. This fix will be available in the next update dropping soon. 

Thanks again!
