### ISSUE TITLE
A Frustrating Start with the Ollie Theme

### ISSUE THREAD

**Issue by wschaapman** [OllieWP/ollie#168]
As a newbie with FSE, I wanted to start with the Ollie theme. So, I created a new website and installed the Ollie theme. However, I then had to jump into the videos to create the site. Each video mentioned a setup wizard, but I couldn't find it. After some checking on the internet, I discovered that the wizard is no longer part of the theme.

It would have been nice to know this beforehand. A simple message above all the videos informing users that the wizard is no longer available would have prevented my frustration and saved me a lot of time.

**Comment by mikemcalister** [comment]
Hey @wschaapman, really sorry about that. We've been so tied up getting Ollie Pro out the door that we haven't had time to update those videos yet. 

For clarity, it _was_ in the theme, but there was a lot of hurdles with it at the WordPress.org repo, so we pulled it out. We weren't quite sure what the fate of it would be, but ultimately, we put it in Ollie Pro. 

Apologies for the confusion, truly. I'll be updating those videos one by one over time to reflect our new setup.
