### ISSUE TITLE
Feedback on Ollie 1.1.1 - uodate of 28 June 2024

### ISSUE THREAD

**Issue by DecimusBurton** [OllieWP/ollie#169]
For what its worth here is some feedback on the update 1.1.1 of 28 June 2024 following update of BajanThing.com

I like the bullets on the sub menu item for mobile - I wish we could collapse the sub-menus on mobile.

I think with 1.1.1 base level font at 1.165rem is a little too small - at least for the audience of BajanThing.com.  In v1.1.0 base text was 1.3rem.

The beauty of global Typography is that I should be able to tweak the sizes so I have bumped base text back to what it used to be 1.3rem.  I've also bumped down the H1 to 2rem (from 3.5rem) and H2 to Medium 1.65 (from 2.75 rem) and left H3 at Medium 1.65.

I am seeing an issue with the **Page Template** for the **H1 Title Heading** - The H1 Title is not transferring from global style to the Page Template.  The size is set to default so it should be picking up the Global H1 style - however its is not so I have had to manually change the Title H1 to 2 rem on the Page Template but that does not seem to have fixed it …. On the template the text size has reduced but not on the actual pages.  The Title is still big text.  It seems to be only an issue with H1 on the Page Template.

The final comment I am not sure if its Ollie 1.1.1 related or WP 6.5.4 related.  Prior to updating to Ollie 1.1.1 I has set the feature image block to have a shadow.  With the update I have lost the feature image shadow.... hoho.

**Comment by DecimusBurton** [comment]
Had another play this morning.  It does seem as if the H1 default does not transfer to the Page template.  I got it fixed by manually adding a custom sizing.   With a clear head I was able to fix this:  "On the template the text size has reduced but not on the actual pages" - I had forgottent to change the manual sizing in the cusotm page (Page with sidebar)!

**Comment by DecimusBurton** [comment]
One more for you..... this may be a WP bug?  For a few Pages where we have a cover image and H1 - we have added a feature image and then used the Use Feature Image option within the cover block.  This is so that in the search results that all the resulting page match - Our general style is we have a feature image on most posts and pages:  As an example see: https://www.bajanthings.com/homepage-hero-images/

For the cover block, the image used is the feature image and the H1 copy is set to centred.  When you use a feature image as the for the cover image, the H1 copy is not centred.  The copy starts from the centre!

**Comment by mikemcalister** [comment]
Hi Peter, thank you so much for the quick feedback! I'll take a look this afternoon and make any fixes needed to account for some of these notes. If I find anything, I'll update you here as well.

**Comment by DecimusBurton** [comment]
In fact I have off Gutenberg plugin as its messing with the size of the feature images on the home page with or without shadow.

**Comment by mikemcalister** [comment]
Hey @DecimusBurton, I've just released an update to the Ollie theme to fix the H1/global style issue you mentioned. Your global style should now take precedent on the page title H1.

**Comment by mikemcalister** [comment]
> Prior to updating to Ollie 1.1.1 I has set the feature image block to have a shadow

I did remove this style temporarily. WordPress core now has the ability to add shadows via the UI, so I'm going to create a set of shadows through that. Hopefully ready in the next update or two.

**Comment by mikemcalister** [comment]
> I had turned off the Gutenberg plugin.

You are a bold man using that plugin live! 😎 I often find that the bleeding edge of Gutenberg is causing some quirky little issues throughout the UI, so I only turn it on to test features and then turn it off. 

I try to report as many quirks as I find!

I _think_ this resolves the issue here, so I'm going to close it. Feel free to open another ticket if you spot anything else!

**Comment by DecimusBurton** [comment]
You are absolutely correct... I had turned on but it's now firmly off....
too bleeding edge...  had originally had it as Astra Pro had built in time
to read block and comments count....

Current version of gutenberg messes up feature image and pushes them
outside borders on home page.

Will just need to wait patiently for WP core to add in time to read and
comment count

Peter
