### ISSUE TITLE
Inquiry About Non-Profit Discounts for Ollie-Pro Plugin

### ISSUE THREAD

**Issue by btwiue** [OllieWP/ollie#170]
Hi,

I hope this message finds you well. I am reaching out to inquire about the availability of non-profit discounts for the Ollie-Pro plugin. Our organization, DOTMW, is a registered non-profit and we are interested in utilizing the Ollie-Pro plugin to enhance our web presence.

For lack of any other method of contact relating to the Ollie-Pro plugin, I apologize in advance if I missed something. If there is a more appropriate channel for this inquiry, please let me know.

Specifically, we are looking to understand:
1. If there are any discounts available for non-profits.
2. The process to apply for such a discount, if available.
3. Any documentation or verification needed from our side to qualify.

Thank you for your time and assistance. We look forward to your response.

Best regards,

David Vogel
Web Developer
Antiochian Diocese of Toledo & Midwest

**Comment by dvogeldev** [comment]
Please close this issue, mined the hidden nugget from the website
