### ISSUE TITLE
1.1.3 "Improve line height styling" broke the styling of my site

### ISSUE THREAD

**Issue by spoetnik** [OllieWP/ollie#173]
**Describe the bug**
The lineheight of a normal <p> is super small. Even overlapping

**To Reproduce**
Upgrade from 1.1.0 to 1.1.3
Look at a <P> somewhere on your site
The lineheight is to small

**Expected behavior**
I hope an update of Ollie theme won't mess up the styling of my site.

**Screenshots**
Ollie 1.1.0
<img width="1382" alt="Screen Shot 2024-07-16 at 20 43 48" src="https://github.com/user-attachments/assets/5ab6e9e2-4d60-4861-bc92-5fce0f86a0ae">

Ollie 1.1.3
<img width="1382" alt="Screen Shot 2024-07-16 at 20 45 19" src="https://github.com/user-attachments/assets/5208b968-bbaa-46ec-8a1c-91dcbd033c8b">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 126.0.6478.127 (Official Build) (x86_64)

Reverting back to an old version reverts the problem

**Comment by mikemcalister** [comment]
@spoetnik Hey Martjin, could you share your website with me so I can take a look? Even better, if you could copy that page section for me and paste the blocks here, I can troubleshoot it quicker.

**Comment by spoetnik** [comment]
Sorry for the late reply. 

This is the code of the section:

`<!-- wp:group {"align":"wide","style":{"spacing":{"blockGap":"0","padding":{"right":"0","left":"0","top":"0","bottom":"0"}}},"layout":{"type":"flex","orientation":"vertical","verticalAlignment":"top"}} -->
<div class="wp-block-group alignwide" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><!-- wp:columns {"align":"wide","style":{"spacing":{"margin":{"top":"0px","bottom":"0px"},"blockGap":{"top":"var:preset|spacing|large","left":"var:preset|spacing|large"}}}} -->
<div class="wp-block-columns alignwide" style="margin-top:0px;margin-bottom:0px"><!-- wp:column {"className":"is-style-column-box-shadow link","style":{"spacing":{"blockGap":"var:preset|spacing|medium","padding":{"top":"var:preset|spacing|medium","right":"var:preset|spacing|small","bottom":"var:preset|spacing|medium","left":"var:preset|spacing|small"}},"elements":{"link":{"color":{"text":"var:preset|color|primary-accent"}}}},"backgroundColor":"main","textColor":"primary-accent"} -->
<div class="wp-block-column is-style-column-box-shadow link has-primary-accent-color has-main-background-color has-text-color has-background has-link-color" style="padding-top:var(--wp--preset--spacing--medium);padding-right:var(--wp--preset--spacing--small);padding-bottom:var(--wp--preset--spacing--medium);padding-left:var(--wp--preset--spacing--small)"><!-- wp:group {"style":{"dimensions":{"minHeight":"100%"}},"layout":{"type":"flex","orientation":"vertical","verticalAlignment":"space-between","justifyContent":"center"}} -->
<div class="wp-block-group" style="min-height:100%"><!-- wp:group {"className":"overflow-hidden","style":{"spacing":{"blockGap":"var:preset|spacing|small"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group overflow-hidden"><!-- wp:image {"id":487,"aspectRatio":"4/3","scale":"cover","sizeSlug":"large","linkDestination":"custom","className":"zoom is-style-default"} -->
<figure class="wp-block-image size-large zoom is-style-default"><a href="https://rib-actie.nl/ribvaren/"><img src="https://rib-actie.nl/wp-content/uploads/2023/12/4M6A4347-1024x683.jpg" alt="Rondvaarten voor de kust van Scheveningen. Het perfecte bedrijfsuitje, vrijgezellenfeest of familietuitje" class="wp-image-487" style="aspect-ratio:4/3;object-fit:cover"/></a></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"fontSize":"base"} -->
<h3 class="wp-block-heading has-base-font-size">RIB-Powerboat varen</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Iedereen kan de zee op! Ben je alleen of met z’n 2en, vriendengroepen, familieuitjes of wil je een privetour? Beleef de ultieme kick van het RIB- powerboot varen voor de kust van Scheveningen.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|small"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:separator {"className":"is-style-separator-dotted","backgroundColor":"primary"} -->
<hr class="wp-block-separator has-text-color has-primary-color has-alpha-channel-opacity has-primary-background-color has-background is-style-separator-dotted"/>
<!-- /wp:separator -->

<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|small"}},"layout":{"type":"flex","flexWrap":"wrap","justifyContent":"center"}} -->
<div class="wp-block-group"><!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="https://rib-actie.nl/ribvaren/">Meer info!</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"className":"is-style-column-box-shadow link","style":{"spacing":{"blockGap":"var:preset|spacing|medium","padding":{"top":"var:preset|spacing|medium","right":"var:preset|spacing|small","bottom":"var:preset|spacing|medium","left":"var:preset|spacing|small"}},"elements":{"link":{"color":{"text":"var:preset|color|primary-accent"}}}},"backgroundColor":"main","textColor":"primary-accent"} -->
<div class="wp-block-column is-style-column-box-shadow link has-primary-accent-color has-main-background-color has-text-color has-background has-link-color" style="padding-top:var(--wp--preset--spacing--medium);padding-right:var(--wp--preset--spacing--small);padding-bottom:var(--wp--preset--spacing--medium);padding-left:var(--wp--preset--spacing--small)"><!-- wp:group {"style":{"dimensions":{"minHeight":"100%"}},"layout":{"type":"flex","orientation":"vertical","verticalAlignment":"space-between","justifyContent":"center"}} -->
<div class="wp-block-group" style="min-height:100%"><!-- wp:group {"className":"overflow-hidden","style":{"spacing":{"blockGap":"var:preset|spacing|small"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group overflow-hidden"><!-- wp:image {"id":894,"aspectRatio":"4/3","scale":"cover","sizeSlug":"large","linkDestination":"custom","className":"zoom is-style-default"} -->
<figure class="wp-block-image size-large zoom is-style-default"><a href="https://rib-actie.nl/vergaderen-op-het-strand/"><img src="https://rib-actie.nl/wp-content/uploads/2024/02/Bedrijfsuitje-RIB-powerboat-768x1024.jpg" alt="Bedrijfsuitjes bij RIB-powerboot varen Scheveningen" class="wp-image-894" style="aspect-ratio:4/3;object-fit:cover"/></a></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"fontSize":"base"} -->
<h3 class="wp-block-heading has-base-font-size">Bedrijfsuitjes</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Met collega`s lekker uitwaaien voor de kust van Scheveningen? Een “heisessie” op het strand en dan met volle snelheid over zee, de dag kan afgesloten worden met een BBQ op het strand.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|small"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:separator {"className":"is-style-separator-dotted","backgroundColor":"primary"} -->
<hr class="wp-block-separator has-text-color has-primary-color has-alpha-channel-opacity has-primary-background-color has-background is-style-separator-dotted"/>
<!-- /wp:separator -->

<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|small"}},"layout":{"type":"flex","flexWrap":"wrap","justifyContent":"center"}} -->
<div class="wp-block-group"><!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="https://rib-actie.nl/vergaderen-op-het-strand/">Meer info!</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"className":"is-style-column-box-shadow link","style":{"spacing":{"blockGap":"var:preset|spacing|medium","padding":{"top":"var:preset|spacing|medium","right":"var:preset|spacing|small","bottom":"var:preset|spacing|medium","left":"var:preset|spacing|small"}},"elements":{"link":{"color":{"text":"var:preset|color|primary-accent"}}}},"backgroundColor":"main","textColor":"primary-accent"} -->
<div class="wp-block-column is-style-column-box-shadow link has-primary-accent-color has-main-background-color has-text-color has-background has-link-color" style="padding-top:var(--wp--preset--spacing--medium);padding-right:var(--wp--preset--spacing--small);padding-bottom:var(--wp--preset--spacing--medium);padding-left:var(--wp--preset--spacing--small)"><!-- wp:group {"style":{"dimensions":{"minHeight":"100%"}},"layout":{"type":"flex","orientation":"vertical","verticalAlignment":"space-between","justifyContent":"center"}} -->
<div class="wp-block-group" style="min-height:100%"><!-- wp:group {"className":"overflow-hidden","style":{"spacing":{"blockGap":"var:preset|spacing|small"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group overflow-hidden"><!-- wp:image {"id":899,"aspectRatio":"4/3","scale":"cover","sizeSlug":"large","linkDestination":"custom","className":"zoom is-style-default","style":{"layout":{"selfStretch":"fixed","flexSize":null}}} -->
<figure class="wp-block-image size-large zoom is-style-default"><a href="https://rib-actie.nl/vrijgezellen/"><img src="https://rib-actie.nl/wp-content/uploads/2024/02/Vrijgezel-overboord-RIB-powerboat-edited-768x1024.jpg" alt="Vrijgezel over boord in zee" class="wp-image-899" style="aspect-ratio:4/3;object-fit:cover"/></a></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"fontSize":"base"} -->
<h3 class="wp-block-heading has-base-font-size">Vrijgezellenfeesten</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Spectaculaire RIB- powerboat tochten + een ludieke “vrijgezel overboord”. Onze zgn. “rib-dip” is echt hilarisch.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Het varen is uit te breiden met bier-arrangementen, BBQ’s op het strand en diverse activiteiten.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|small"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:separator {"className":"is-style-separator-dotted","backgroundColor":"primary"} -->
<hr class="wp-block-separator has-text-color has-primary-color has-alpha-channel-opacity has-primary-background-color has-background is-style-separator-dotted"/>
<!-- /wp:separator -->

<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|small"}},"layout":{"type":"flex","flexWrap":"wrap","justifyContent":"center"}} -->
<div class="wp-block-group"><!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="https://rib-actie.nl/vrijgezellen/">Meer info!</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"className":"is-style-column-box-shadow link","style":{"spacing":{"blockGap":"var:preset|spacing|medium","padding":{"top":"var:preset|spacing|medium","right":"var:preset|spacing|small","bottom":"var:preset|spacing|medium","left":"var:preset|spacing|small"}},"elements":{"link":{"color":{"text":"var:preset|color|primary-accent"}}}},"backgroundColor":"main","textColor":"primary-accent"} -->
<div class="wp-block-column is-style-column-box-shadow link has-primary-accent-color has-main-background-color has-text-color has-background has-link-color" style="padding-top:var(--wp--preset--spacing--medium);padding-right:var(--wp--preset--spacing--small);padding-bottom:var(--wp--preset--spacing--medium);padding-left:var(--wp--preset--spacing--small)"><!-- wp:group {"style":{"dimensions":{"minHeight":"100%"}},"layout":{"type":"flex","orientation":"vertical","verticalAlignment":"space-between","justifyContent":"center"}} -->
<div class="wp-block-group" style="min-height:100%"><!-- wp:group {"className":"overflow-hidden","style":{"spacing":{"blockGap":"var:preset|spacing|small"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group overflow-hidden"><!-- wp:image {"id":893,"aspectRatio":"4/3","scale":"cover","sizeSlug":"large","linkDestination":"custom","className":"zoom is-style-default"} -->
<figure class="wp-block-image size-large zoom is-style-default"><a href="https://rib-actie.nl/arrangementen/"><img src="https://rib-actie.nl/wp-content/uploads/2024/02/BBQ-op-het-strand-RIB-powerboat-1024x681.jpg" alt="BBQ op het strand" class="wp-image-893" style="aspect-ratio:4/3;object-fit:cover"/></a></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"fontSize":"base"} -->
<h3 class="wp-block-heading has-base-font-size">Arrangementen</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>BBQ’s op het strand, Powerkiten, e-chopper of Expeditie Robinson? Combineer het RIB- powerboot varen met één van onze activiteiten en stel een arrangement samen. Wij helpen je er graag mee!</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|small"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:separator {"className":"is-style-separator-dotted","backgroundColor":"primary"} -->
<hr class="wp-block-separator has-text-color has-primary-color has-alpha-channel-opacity has-primary-background-color has-background is-style-separator-dotted"/>
<!-- /wp:separator -->

<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|small"}},"layout":{"type":"flex","flexWrap":"wrap","justifyContent":"center"}} -->
<div class="wp-block-group"><!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="https://www.rib-actie.nl/arrangementen/">Meer info!</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->`

**Comment by spoetnik** [comment]
I fixed it, and I will try to describe wat I did so other can have this as a reference if they have the same problem after an update.

I had to define the Line-height for a paragraph in the style setting.

Click the following in the WP-admin:
Appearance -> Editor. Styles -> Edit styles (Pencil icon), Blocks (in the righthand panel), Paragraph, Set the Line-height to 1.5 and Save
