### ISSUE TITLE
Woocommerce Patterns & Support

### ISSUE THREAD

**Issue by FunkyCss** [OllieWP/ollie#175]
Hello,

I am a heavy user of WooCommerce and currently work with classic themes. However, I am actively testing some features in Full Site Editing (FSE) and I believe it has great potential.

I noticed that many new FSE themes, such as Ollie, do not provide WooCommerce patterns or full pages. Although I haven't used the pro version yet, I couldn't find any references to WooCommerce support on your website.

I would like to suggest adding full WooCommerce support to your roadmap, including design patterns and full pages (excluding functionality).

I would appreciate your feedback on this or any plans you might have for WooCommerce integration.

Kind regards,  
Andreas

**Comment by mikemcalister** [comment]
Hi Andreas, 

Thanks for writing in. We do not have any plans to integrate with WooCommerce at this time. There are many considerations that go into making a theme integrate well with WooCommerce, and we don't want to define Ollie as a WooCommerce theme this early on. 

That doesn't meant that Ollie won't work with WooCommerce, but we won't be optimizing for it at this time.
