### ISSUE TITLE
Menu takes to much space in smaller screens

### ISSUE THREAD

**Issue by boboz** [OllieWP/ollie#21]
Lovely theme!

Potential to improve for smaller laptop screens? Below screenshot from a 14¨ 1920 x 1080 screen and I think the menu area takes a lot of space from the initial screen appearance. Second screenshot is what I think it should look like. This is with menu scrolled away.

![screenshot-demo olliewp com-2023 04 20-10_37_17](https://user-images.githubusercontent.com/141707/233315205-2b64b7f5-d0e6-49e1-88c7-478c6127bbc7.png)

![screenshot-demo olliewp com-2023 04 20-10_02_39](https://user-images.githubusercontent.com/141707/233315290-dc2c492d-4179-4dc1-a2ae-0f36ca1095b4.png)

**Comment by mikemcalister** [comment]
Hey there! You can easily change that padding in the editor. Here's a video of how to do that. Once you hit save, your theme will use your new padding, and it will scale accordingly on smaller devices.

https://user-images.githubusercontent.com/1415737/233491760-fc6779d8-05a9-499d-97ab-c2f96843d8fb.mp4

**Comment by boboz** [comment]
Ok, thank's for taking the time.
