### ISSUE TITLE
Displaying similar articles on single post buggy

### ISSUE THREAD

**Issue by heldenhaft1** [OllieWP/ollie#22]
Hi,

it seems that the display of similar posts on the single post page is incorrect. I see only images - even on the demo page. (see screenshot)

Many greetings

<img width="949" alt="Bildschirmfoto 2023-04-28 um 22 25 16" src="https://user-images.githubusercontent.com/132102989/235248760-bf674037-c46a-49ea-9a52-5a332c4ac62b.png">

**Comment by mikemcalister** [comment]
Hey there, thanks for reporting this! I've just pushed a fix to the develop branch, and I'll make sure this is included in the next release. 👍
