### ISSUE TITLE
Loving  this beta

### ISSUE THREAD

**Issue by greening** [OllieWP/ollie#23]
I do love this theme, and its supporting documentation.

Maybe you have it, and I've not found it. I would love a group (in my case episodes with pictures) that has a "more..." at the bottom which would expand the list without changing the page.

I could program this stuff myself, but would rather pay you for your work and support, so bravo for tackling the FSE commercial theme challenge. I have been sitting around waiting for something to switch my site to, still running on a long-in-the-tooth unsupported iFeature Pro (Cyberchimps) theme. Watching this FSE thing unfold, and not seeing anything that strikes my fancy yet, other than Ollie.

**Comment by mikemcalister** [comment]
Hey Dan, 

Thanks for checking out Ollie! Can you link me to an example of the kind of box you're looking for. I think I have an idea, but an example would be great so I can log it for creation. Thanks!

**Comment by greening** [comment]
Hi Mike,
I don't see an example of what I'm looking for immediately on the web. The way you could think of it is...
Maybe a start with a single row that includes 3 columns with image, title, date on each "post box." and a "more..." button in the lower right of that query loop. When you click it, it would perhaps add 3 more rows and "more..." would appear at the bottom right of those 4 total rows, etc.
Dan

**Comment by mikemcalister** [comment]
Logged this in our feedback doc! Closing the ticket for now.
