### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by saliksik** [OllieWP/ollie#24]
Greetings!

I wanted to express my gratitude for developing such an impressive WordPress block theme. I was hoping you could assist me with adding a search box or the magnifier to the header. As a newcomer to block themes, I am encountering difficulties in accomplishing this task.

Thank you for your assistance.

**Comment by mikemcalister** [comment]
Hey there, 

Here's a quick video showing how you can add a search to the navigation. If you add the search to the navigation, it can also be seen in the mobile menu. 👍

https://user-images.githubusercontent.com/1415737/235552875-1f69f8db-efa3-49c6-ac95-c15d565948da.mp4
