### ISSUE TITLE
Margin and padding media queries

### ISSUE THREAD

**Issue by bm-jakob** [OllieWP/ollie#25]
**Is your feature request related to a problem? Please describe.**
No and yes. The problem I'm facing with block themes in general, is that you can only set spacing values for one screen type. So let's say I make 100px margin-top on an element, now it'll look ridiculous on a mobile device.

**Describe the solution you'd like**
It would be awesome to be able to set the spacing values for multiple breakpoints. Would be cool if you could define the breakpoints yourself in the backend perhaps?

**Describe alternatives you've considered**
An alternative for me personally is not using block themes. But I want to!

**Additional context**
Nothing to report.

I'm open to hear more thoughts on this!

**Comment by mikemcalister** [comment]
Hey Jakob, 

Thanks for writing in. Yeah, unfortunately we don't have responsive controls in WP core yet.

For this reason, I would avoid using 100px and instead use the default margin/padding sliders which are connected to fluid spacing. So any value you set for desktop will automatically scale down for tablet and mobile styles, unlike with px values. 

<img width="312" alt="Screen Shot 2023-05-01 at 4 05 44 PM" src="https://user-images.githubusercontent.com/1415737/235531264-4937fe77-3d57-416b-a0db-2f08abf4a1c9.png">

**Comment by bm-jakob** [comment]
Would be awesome if WP added support for media queries on these sliders.

Thanks for the reply!
