### ISSUE TITLE
Header Patterns not available in new Template Part Header 

### ISSUE THREAD

**Issue by pmmueller** [OllieWP/ollie#26]
**Describe the bug**
The Header Patterns are not available when adding a new Template Part Header. They seem to be wired to Templates only. 

**To Reproduce**
1. Go to 'Website Editor > Template Parts'
2. Click on 'Manage All Template Parts'
3. Click on 'Add'
4. Give it a name and add a new template part Header 
5. Edit the new Header 
6. Open the Block Inserter 
7. Change to Patterns 
8. Header Patterns are not available 

**Expected behavior**
Shouldn't the Header Patterns be available when adding a Template Part, just like they are when I open a Template, select the Header and choose Header > Replace?  

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari 
 - WP 6.2 
 - Ollie 0.1.0 

---
I report this what I believe to be a bug because I really like Ollie after playing with it for about an hour. 
Thank you for this very promising block theme.

**Comment by mikemcalister** [comment]
Hey Peter! Thanks for the heads up. I've just made a few changes and pushed them to the develop branch. You can check out the fix there, or you can wait until I push a new release, which should be in a few days. You should now be able to access those patterns site-wide. 

Just another little tip that may be helpful. When you want to replace the header design, you can use this little trick to quickly replace the design. 

<img width="1503" alt="Screen Shot 2023-05-01 at 4 01 22 PM" src="https://user-images.githubusercontent.com/1415737/235530831-35f395a7-267c-4358-af7c-4cbe881b5848.png">

Click on the Header template part, click the dotted menu, and then click Replace Header. It will bring up a pop-up where you can choose a new header design. 😎

**Comment by pmmueller** [comment]
Thanx for the quick reply and I will check out the update one way or the other. 

Also thanx for the tip and the screenshot. I know "Replace Header" and I use it, but when I show changing a header in the website editor to newbies I prefer the other workflow: I first explain that a template part is a reusable module and then let them consciously create an empty template part. In the next step they fill the template part with a pattern. That way they experience the difference between these things and have created a reusable template part that they'll remember when they see it. 

If on the other way you just choose a pattern in Replace Header the website editor will create a template part with the same name as the pattern without telling anyone. Which is fine. 

But that way newbies don't experience the difference between a template part and a pattern. They don't know that a template part exists for them to reuse in the next template. 

So when they change the header in the next template I've seen them ignoring the template part presented at the top of the list and head straight for the pattern again, as that seemed to work well the first time. 

So now they have two template parts with identical names and don't even know that they exist. And that's where confusion begins, especially when they repeat this procedure for three or more templates creating x identical template parts. 

A lot of question marks popping up when they finally at some stage open the list of template parts and see x identical entries ... 

So thanx for fixing that ;)

**Comment by mikemcalister** [comment]
Hey Peter, thanks for sharing that additional context, very helpful. The fix should be available in a release soon!
