### ISSUE TITLE
Feedback & Site Colors Question

### ISSUE THREAD

**Issue by VFlame44** [OllieWP/ollie#28]
Hi Mike, **Awesome job on theme!** ... I appreciate it & the education you are putting out!

If I want to **_add a color scheme_** in the **"styles" folder** for a project coming up, _based on their current logo colors_ ...

Do you have a **Color Legend** or any type of **Mapping**, for how colors line up with the **Ollie site design elements**?

Ollie Color Names
-------------------
○ base
○ main
○ main-accent
○ primary
○ primary-accent
○ secondary
○ tertiary

Thank you very much Mike,
Larry

**Comment by mikemcalister** [comment]
Hey Larry, 

Thanks for the feedback! I don't have a style reference like you mentioned yet. I'll get something together for that. 

In the mean time, you can go into the Global Styles panel in the site editor and click around to see what the colors control. Here's a quick video tutorial on how to do that.

https://user-images.githubusercontent.com/1415737/236659023-2594b336-4a5a-46f0-912d-1062f3fa57a4.mp4

**Comment by espiat** [comment]
@VFlame44 

Hi.

I faced exactly the same problem. For a client who already had a color palette.

I then tried to build a child theme with a palette added to the parent theme.

Thats not OK. You can add a color palette to the child theme, but this will wipe out all other parent theme color schemes. Duotone tones can be added to the parent theme with a child theme.json, for example. The color palettes don't seem to work.

I've been dealing with this for several hours.

All attempts with a theme.json via a plugin also didn't work.

**Comment by VFlame44** [comment]
@espiat 

Hey!

I am planning on just changing the main theme.json (no child theme) -or- create an additional color palette in the "styles" folder.

Mike's video shows how you can just click on a color and change it, the theme elements reference the colors via global variables that are automatically set from the colors. I didn't even think of doing it this way, but **it works!** I think the only thing is that these changes are stored in the database (not sure on this, but I think so).

There are two ways that I know of that you can change theme files to deploy your color them.

1) is to change the main color palette in theme.json 
	"settings": {
		"color": {
			"palette": [
				{
					"name": "Primary",
					"slug": "primary",
					"color": "#4d34fa"  <=====
				},
        etc.

2) is to change or add an alternate color palette in the "styles" folder. Use can access these additional color styles in "editor" mode via "Browse styles  >" in the styles menu on the right.

	"title": "Orange",
	"settings": {
		"color": {
			"palette": [
				{
					"name": "Primary",
					"slug": "primary",
					"color": "#F45E02"  <=====
				},


One thing to make **note** of, is that if you make changes to the theme.json or the alternate palettes in the styles folder ... is that some times you have to do a **"reset"** in the editor to see your changes that you made in the files.  

While in the "editor", click on your current Color Palette you are using to expand the colors, then click on the dot menu, then click on **"Reset colours"** ... this will pickup the colors you have set in the files.

Have a good one!

**Comment by espiat** [comment]
@VFlame44 

I know how to change style in Full site Editor.
But I wanted to add a new palette to all the existing ones.

If you change something in the Ollie Theme folder, it can happen that it will be overwritten with the next update. That's the problem.

I don't want to change the theme files. That's what the child theme is for.

**Comment by espiat** [comment]
Ultimately, it's a Coe discussion and has little to do with the theme.

**Comment by mikemcalister** [comment]
Yeah unfortunately that issue with color palettes in child themes is a core thing. You'd have to copy the color palettes from the parent theme into the child theme, and then add your own on top of that.

**Comment by Ren2049** [comment]
I find the color naming a bit weird because it's not how primary, secondary etc. is normally used in design. I've noticed that TT3 uses a similar scheme. Is compatibility the reason why you use it?

It's meant to indicate color distribution, with primary being the most widely used color in a document/section, followed by secondary and tertiary which is typically your accent color. 

It's not meant to be hardcoded but changes depending on the page/section or document you design. Color naming in core is imo a major bug because it creates all kinds of problems and only confuses designers who have learned it the proper way.

**Comment by mikemcalister** [comment]
Yeah, I'm just following core's lead on this one. It's a very difficult discussion with many opinions involved. I think we're going to get a solution soon where the naming actually doesn't matter so much, as it's routed to a variable in a more efficient way.
