### ISSUE TITLE
Remove page title after applying pattern to new page

### ISSUE THREAD

**Issue by lisasorenson** [OllieWP/ollie#29]
Hello! 
Loving this theme just starting to play around with it. I'm having trouble finding where I can remove the default page title once I apply for example, the About me page pattern, to a new page I don't see option to remove that default top title once I've added the pattern to a new page? 
Thanks!

**Comment by lisasorenson** [comment]
I think after digging around I found answer. After adding pattern to new page I went to right side page menu under the template section and choose no page title.

**Comment by VFlame44** [comment]
That is the correct way to do it!  

"No Page Title" will use the page template that has page title removed.
