### ISSUE TITLE
Many warnings in the console when one of the pattern groups is accessed

### ISSUE THREAD

**Issue by bseddon** [OllieWP/ollie#36]
Many of these warnings appear in the  development tools console when one of the pattern groups is accessed:

react-dom.js?ver=18.2.0:73 Warning: Encountered two children with the same key, `grayscale`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

 - WordPress version 6.2.1
 - OS: Windows 11
 - Browser: Chrome
 - Version 113

The problem is the name of a slug in themes.json.  Change settings.color.duotone[].slug from 'grayscale' to, say, 'grayscalex' the problem goes away. 

I'm not using any blocks or plugins. So far, this happens on any sites in which Ollie has been activated.

**Comment by mikemcalister** [comment]
Hey Bill, thanks for the report. I'm not able to reproduce on my end. I've tried a few different things with the grayscale duotone, but not getting any console errors. 

Any other details you can provide about when you're seeing this? Do you have any other plugins installed that may also be registering a duotone color with the same name?

**Comment by bseddon** [comment]
Thanks for your prompt response.  Disabling all plugins does not resolve the problem.  For good measure, the functions.php code ihas been emptied and the problem still occurs.  However, when starting with a fresh copy of WordPress and installing/activating the theme the issue does not appear as you would expect.  

Pointing the new installation at the database of the old installation the problem does not occur either which indicates there's nothing about the database causing the issue.

Clearly the problem is mine.  If you encounter a similar scenario and learn the cause it will be great to find out.

**Comment by mikemcalister** [comment]
Ok cool. I'll definitely keep an eye out for it.

**Comment by bseddon** [comment]
The issue seen and reported here is because we use the 'SCRIPT_DEBUG' constant set to true in development environments.  Although this issue is now closed, I'm adding this comment in case anyone else encounters the same problem.

As you will know, when this constant is set, WordPress will use 'dev' rather than minified version of scripts and CSS files.  It seems setting this constant to true does not play well with the react components.  Or, maybe, it just hides an issue.

The underlying issue is that WordPress defines a duotype of 'grayscale' in ./wp-includes/theme.json.  Because Ollie includes this same definition, the styleProvider function in component.js wants to report this as an warning.  The actual warning is suppressed unless the DEBUG_SCRIPT constant is set to true.

This screenshot shows the properties added by the the style provider function. In it you can see the two grayscale definitions.  The first instance is from WP the second from Ollie.  This assertion can be verified by reviewing the values of the respective properties and the duotone values around them which correspond to the entries in the respective theme.json files.

![ollie-duotypes](https://github.com/OllieWP/ollie/assets/1221824/c31fb6c5-ae5b-47f7-9056-142ad4c84bc7)
