### ISSUE TITLE
CSS Tweak for Pagination

### ISSUE THREAD

**Issue by moggiex** [OllieWP/ollie#37]
The below fixes the issue with the pagination buttons at the bottom of blogs where the numbers that are not links have no padding and the three dots "..." have no [padding either.

Looked at the source, loads of CSS files, so thought better to leave here for you Mike :)

Can be confirmed if you tweak a query loop to show one post for >5 published posts to get the pagination to show fully.

```
span.page-numbers.dots,
span.page-numbers.current {
    padding: 0.5em
}
```
M

**Comment by mikemcalister** [comment]
Thanks for the heads up! Just pushed a fix to the `develop` branch. It will be available in the next release shortly!
