### ISSUE TITLE
Template Usage & Smooth Riding for Ollie Users!

### ISSUE THREAD

**Issue by VFlame44** [OllieWP/ollie#38]
Hey Mike,

Again, I am loving Ollie (design & education)! Thank you!

In regards to what to start out with in Templates, I have the following Notes & Suggestions.

I am actually Ok with how you are doing things now, but that's because I have enough knowledge & experience now with Block Themes.

The following is more for people newer to block themes, but also to make Ollie a smooth ride for all!!!

Notes on your latest change (github theme update)
------------------------------------------------------------------------------------------
Using "Front Page" Template is good IMO, I like it ... it is an Intuitive Name!  And I think WordPress gives some extra priority to that template in the scheme of things.

Notes on How WordPress is Working (Templates it is using & What is displayed)
---------------------------------------------------------------------------
Depending on what you choose in the Settings > Reading >"Your homepage displays" section

○ If choose "Your latest posts" ==> When you click on Site Icon/Title you get Only what you have in the "Front Page" template (exception: WordPress does squeeze in the Content from your Latest Post)

○ If choose "A static page > Homepage   (with an Existing Page) ==>  it uses the "Front Page" template (for Site Icon/Title click & Homepage menu item)

○ If choose "A static page > Posts page (with an Existing Page) ==>  it uses the "Posts Page" template (for Blog menu item)

Just a Side Note for people
--------------------------------------
○ If while Creating/Editing a Page ... and you choose "Default template" for your template, you are actually selecting ==>the "Page" Template.

So ...
--------------------------------------
Currently in your **"Front Page" template** ... **there is No "Post Content" Block**, so **all you get is the current Ollie content** you have in there. (Except in the case where you do not select a Static Page, then WordPress squeezes in "content of the latest post")

So Bottom Line ....
--------------------------------------
At some point the **"Front Page" template will need to be emptied by the User** & a **"Post Content" block be put in there**. And the **User can add in anything else they might want** unique about there "Front Page".  They will want to get their content on the "Front Page", and I think it is more likely they will want to do content editing outside of the Site Editor & Just put a Content Block in the "Front Page" template ... and they may want to put a Query Loop, etc. in there too.  In any case, they will be changing it.

**Here is what I propose** (no matter what you start out with in the "Front Page" template) for Ollie
--------------------------------------------------------------------------------------------------------
==>Use your **Ollie Theme "Theme Details" page** with some **added buttons to help Users with setup**.

The results of doing something like **this will do 3 things**:  (1) Smooth out the setup for Users, (2) Educate them on how Block Themes are working with WordPress, and (3) help make Ollie even a more GoTo theme!  It seems to go with all the great things you are doing Mike!

Attached is a **mock-up of Ollie "Theme Details" screen** (with **helper buttons**, ideas for what you could provide):

![Ollie Theme Details](https://github.com/OllieWP/ollie/assets/129994813/599b8da2-9470-442e-a862-4d7cf3e428bb)

Six (6) Potential Added Buttons - And of course all the programming behind them!
-------------------------------
○  Empty "Front Page" template (and put Content Block in "Front Page" template).

○  Create Example "Home Page" & "Blog Page" (and Set as Static) O-Home, O-Blog ... using O-Xxxx will make them unique.

○  Create Starter Pages (and Set as Static), people can then modify Names & Content at will ... O-Home, O-About, O-Contact, O-Blog, etc.

○  Load your Demo Pages (and Set as Static), people can then modify Names & Content at will ... O-Home, O-About, O-Contact, O-Blog, etc.

○  Button (to Add a couple Blogs - on how WordPress Works, like the Template stuff, etc ... what ever you think would be good). They can delete the Blog Posts when they are done with them.

○  Button (to your Docs Page).

Ok, **you get the idea now!**

I don't know how easy this stuff is to code (I have not done any of it), but I know You can do it if you think it is the way to go!

I did search around for coding ideas ... I think the following might come into play:
Insert posts with: wp_insert_post( $post )
Specify Static Pages with: update_option($option, $value)

**Great job Mike**, let me know if you want to bounce any ideas!
Larry

**Comment by mikemcalister** [comment]
Really great feedback here, Larry! I really appreciate the time and thought you put into this. 

You've hit the nail on the head with the front-page.html issue. 

- To get that impressive out of the box experience, where the homepage is already set up and ready to edit, we have to use front-page.html (or home.html). But, unfortunately, that makes the Reading settings a little funny. 
- We could go back to the old way of doing things and not set a front-page.html, but then you run into the classic "Hey my theme doesn't look like the demo!" problem. 
- So we'll keep front-page.html for now, and we'll just figure out a smooth way to help users change the page if/when they want to. 

One way is an onboarding wizard, as you suggest. I've started designing something like this, but it's not quite ready yet. In the short term, I think what I'll do is just add some docs and a video to show people how to swap out the homepage. 

I'm going to do a little poking around at this in the next couple of days, I'll let you know what I come up with!

**Comment by VFlame44** [comment]
Hey Mike, Yes, **I agree with everything you are saying too!**  And right, if it comes up completely empty, the user would be like ... did I get the theme I was trying to get & now what do I do! 

I don't want to underestimate the users, but I think some could get a little frustrated/confused if they **Have** to get into "**site editor templates**" immediately on the way in.  Will be nice if you can get them into the Patterns & Blocks as soon as possible!  Like ...

**Install Theme > Activate > Go to pages (and start modifications)  -or-  Start inserting patterns (and make modifications)**

Well, anyway, enough said for now ... I think the **docs & video you talked about will be perfect to start with**!

**Comment by VFlame44** [comment]
Great job Mike!  Out of the park & Grand Slam (in baseball terms, haha)!!!
