### ISSUE TITLE
Changing Global Style deletes existing Additional CSS

### ISSUE THREAD

**Issue by waxingmedia** [OllieWP/ollie#39]
**Describe the bug**
Additional Global CSS Styles are deleted upon save after choosing a new style

**To Reproduce**
1. Go to theme customizer
2. Click on styles icons to bring up styles
3. Click vertical ellipse menu and select Additional CSS
4. Add CSS
5. Click SAVE
6. Navigation back to main global styles pane and select "Browse Styles"
7. Select a new styles
8. Click SAVE
9. Click vertical ellipse menu and select Additional CSS to see styles are gone

**Expected behavior**
The style shouldn't be deleted upon style change

**Screenshots**
https://youtu.be/g1VXoOjMmOI

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura 13.3.1
 - Browser : Safari 
 - Version: 16.4

**Comment by waxingmedia** [comment]
Please ignore.

**Comment by waxingmedia** [comment]
I'm reopening this. I still don't understand why styles would be deleted when enabling a different style. If I change to another style and then go back to the original, shouldn't my old styles remain?

**Comment by mikemcalister** [comment]
Hi there, thanks for reporting this. This is actually a bug in WordPress core, and [it has been reported here](https://github.com/WordPress/gutenberg/issues/50685). Hopefully it makes the cut for the next release!

**Comment by waxingmedia** [comment]
I suspected that might be the case. Thanks for the reply! Great theme, BTW!
