### ISSUE TITLE
Changing global style heading does not work

### ISSUE THREAD

**Issue by yarcheek** [OllieWP/ollie#41]
When I change global style settings for headings, more specifically, the font-family, font apereance and line-height (the others are fine) it does not change anything. 

**For example, when chnaging the default font family for all headings to monospace...**
Inspecting heading elements on frontent, I can see that, the class ..wp-block-heading has font-family set to--wp--preset--font-family--primary and overwrites h1, h2, h3... css set to --wp--preset--font-family--monospace.

**Comment by yarcheek** [comment]
It now hit me, that its global styles heading block settings which overwrites it.

So, let me rather ask, why do you have this settings on a block level? Why not to have block style inherit a global style by default?

**Comment by mikemcalister** [comment]
Hey Martin, 

Thanks for the heads up. Looks like this was just a bug I had in theme.json. I'll push an update to the develop branch shortly!

**Comment by mikemcalister** [comment]
I've pushed an update to the`develop` branch with this fix. Feel free to test out, or check it out in the next release. I'll close this for now, but feel free to open it back up if needed.
