### ISSUE TITLE
Add a captions to featured images

### ISSUE THREAD

**Issue by alexeiyakovenko** [OllieWP/ollie#42]
**Is your feature request related to a problem? Please describe.**
Great theme, but there is a small problem: Futured image does not display description that was specified when the image was uploaded.

**Describe the solution you'd like**
Please add the ability to display the description of futured image.

**Additional context**
Some photos need to be captioned, including due to copyright.

**Comment by mikemcalister** [comment]
Hi there, as far as I can tell, that's not a feature of WordPress core. Are you adding featured image captions with a plugin or am I missing something?

**Comment by alexeiyakovenko** [comment]
Hello! Image captions adding when uploading by standard WordPress tools. I used many themes that automatically displayed captions for futured images. How can I do this in the case of your theme? I would be very grateful for your help.

**Comment by verquist** [comment]
I answered this question on Issue #50 => https://github.com/OllieWP/ollie/issues/50
