### ISSUE TITLE
SVG Support plugin not working

### ISSUE THREAD

**Issue by greening** [OllieWP/ollie#44]
**Describe the bug**
SVG Support, which I think is the most popular plugin to support SVG format images, does not work in the Template Editor.

**To Reproduce**
1. Install SVG Support plugin
2. Upload an SVG image to Media Library
3. Edit the Front page in site editor
4. Add the image to a menu bar.
5. Save it (the image won't be visible, saved or not)
6. Visit the site. Image is visible outside the site editor

**Expected behavior**
Image is visible immediate after adding to menu or anything

**Screenshots**

<img width="1276" alt="Screenshot 2023-05-25 at 4 00 56 PM" src="https://github.com/OllieWP/ollie/assets/79808/ee013ce3-d63c-4922-9b31-69608681b462">
<img width="1277" alt="Screenshot 2023-05-25 at 4 00 27 PM" src="https://github.com/OllieWP/ollie/assets/79808/43eb9808-8252-4a91-ae44-c7430c5fe14b">

**Desktop (please complete the following information):**
 - OS: MacOS X M1
 - Browser Chrome

**Additional context**
I'm migrating my company site. I know there's a workaround converting to .webp or whatever. But I suspect I'm not the only person who likes to work with SVG.

**Comment by mikemcalister** [comment]
Hey Dan, thanks for sending this along. I'm using that plugin on a few sites with Ollie and I'm not seeing the same thing. Here's a screenshot with a freshly uploaded SVG in the site editor. 

<img width="1373" alt="Screen Shot 2023-05-31 at 1 15 45 PM" src="https://github.com/OllieWP/ollie/assets/1415737/a9532589-2b86-4fe7-b8fa-734e0fdd9d91">

The image is visible when I upload it, and also when I save and visit the front end. I'm testing on a local dev site, not sure if that helps with troubleshooting on your end. Can you confirm this happens on a clean install as well?

**Comment by verquist** [comment]
Hey Dan, I'm using the "Safe SVG" plugin. I have not had any issues. If you're still having problems, may want to try it instead.
