### ISSUE TITLE
Sticky Header Position Not Working

### ISSUE THREAD

**Issue by harisnadeem** [OllieWP/ollie#45]
**Describe the bug**
I can't fix the position to 'Sticky' for the Header (template part). This is on a fresh installation of WordPress. No additional plugins installed yet, except the Ollie theme.

P.S. I love this beautiful theme and will be using it in my number of simple WP projects that require a very clean and minimalistic look.

**To Reproduce**
1. Go to the Header template part editor
2. Select the 'Group'
3. From the Block Settings sidebar, select 'Sticky' in Position

**Expected behavior**
The header area (entire template part) should act as sticky and should not move up when scrolling down. Right now, the 'Default' and 'Sticky' options act the same.

**Screenshots**
![CleanShot 2023-05-27 at 18 36 18@2x](https://github.com/OllieWP/ollie/assets/5142622/732e7991-18cd-45b9-8ae7-e6b60a8deea7)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Version 113.0.1

**Smartphone (please complete the following information):**
I did not test this on my phone.

**Comment by mikemcalister** [comment]
Hey Haris, thanks for sending this along. Check out [this older issue](https://github.com/OllieWP/ollie/issues/19#issuecomment-1498020773) where we worked through what's going on here. tldr; it's a core thing (as far as I can tell).

**Comment by shrinkray** [comment]
If `position: sticky` could be added to the `<header>` element, the `sticky` value will work. This [post](https://elad.medium.com/css-position-sticky-how-it-really-works-54cd01dc2d46) explains it well. TLDR; the immediate parent contains the sticky element plus others, (`<main>` & `<footer>`) to scroll past.
