### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by ValLynn** [OllieWP/ollie#46]
**Describe the solution you'd like**
BREADCRUMBS

Please add Breadcrumbs to posts and pages.

**Comment by creativefibro** [comment]
That would be a nice touch, for now I am using the Breadcrumb block by Phil Fan. Less plugins and more template built in features is a good plan.

**Comment by mikemcalister** [comment]
We're considering this block for the Ollie plugin, so I'll log the feedback over there. Closing this for now!
