### ISSUE TITLE
Single Sidebar Template Missing from Template Parts

### ISSUE THREAD

**Issue by ValLynn** [OllieWP/ollie#47]
The new Page (wiith Sidebar) states, "To add content to this sidebar, visit the Site Editor and edit the Single Sidebar template." 

There is no template part to edit.

**Comment by mikemcalister** [comment]
So terribly sorry for the delay, Val. You've probably sorted this out by now, but for posterity, the sidebar content can be edited by going to `Appearance > Editor > Patterns > Template Parts > Sidebar`.
