### ISSUE TITLE
Post Featured Image: Optional Caption?

### ISSUE THREAD

**Issue by greening** [OllieWP/ollie#50]
**Is your feature request related to a problem? Please describe.**
I have some images where I'd need to assert copyright (from someone else). Ideally this would be done in a caption. The Post Featured Image block doesn't provide the ability to show a caption. I realize this is a block from the Wordpress group

**Describe the solution you'd like**
When in the site editor, you could set whether the Post Featured Image block would show the #caption from the Media entry. If that field is empty, no space is taken for the image.

If interested, I could write this change. However, I'm not sure how submissions like this get to the Wordpress group.

**Comment by verquist** [comment]
Hey Dan, I ran into the same issue. The workaround I used is to change the "Single" template to not include the featured image at the top of each blog post. Then I add my image to each post, along with any caption I want. I like this approach better anyway. It is much more like the Medium Editor. I can see my image at the top of each post when I'm editing. Before I would only see the title + text of my post.

Hope this helps,
Jim
