### ISSUE TITLE
[Warning] Sidebare template area is not a registered area in site editor

### ISSUE THREAD

**Issue by lushkant** [OllieWP/ollie#56]
**Describe the bug**
The Sidebar template area is not yet a registered area in Site Editor, and it is throwing an error since it is being registered as one at theme.json.
https://github.com/OllieWP/ollie/blob/e7ac9373e7d3f4cf74ab6eded5ebe588cae327da/theme.json#L897-L901

**To Reproduce**
1. Make sure you have `WP_DEBUG` constant defined and set to true. 
2. Go to front or admin.
3. See the error at the top.

**Screenshots**
<img width="1790" alt="Screenshot 2023-07-27 at 5 07 37 PM" src="https://github.com/OllieWP/ollie/assets/18240138/7fed5a04-b6bc-4cdc-9669-02de6583c716">

**Expected and Resolution**
Since there are only three template areas to choose from header, footer, and uncategorized (general). Setting the third area, Sidebar to uncategorized should do it. 

Ready to merge PR #57

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: Sonoma 14.0

**Comment by mikemcalister** [comment]
Hey @lushkant, this will be fixed by registering a Sidebar template part, which can be seen in [this commit](https://github.com/OllieWP/ollie/commit/faac006cac44974b09fbb356752b26bcd2e035f7) on `develop` branch. Thanks for your feedback and PR!

**Comment by lushkant** [comment]
> Hey @lushkant, this will be fixed by registering a Sidebar template part, which can be seen in [this commit](https://github.com/OllieWP/ollie/commit/faac006cac44974b09fbb356752b26bcd2e035f7) on `develop` branch. Thanks for your feedback and PR!

Oh wow noice, didn't knew that. Btw looking forward to testing more of ollie out especially the new onboarding flow. Hopefully, I can help then 🤟
