### ISSUE TITLE
Pagination elements are styled like buttons but do not follow button style settings

### ISSUE THREAD

**Issue by cckto** [OllieWP/ollie#58]
**Describe the bug**
Not sure if this is an oversight or intended behavior: Pagination elements are styled like buttons but do not follow button style settings

**To Reproduce**
1. Go to Site editor
2. Click on Styles button
3. Click on "Colors"
4. Click on "Button"
5. Choose different text and background colors

**Expected behavior**
Since the pagination link blocks are styled to look like buttons, one would expect the above button style settings to apply to them.

**Screenshots**
![2023-07-28 13_09_51-Index ‹ Template Part ‹ Editor  WordPress — Mozilla Firefox](https://github.com/OllieWP/ollie/assets/23368993/1d2efcd1-e120-4a74-a183-82e6ec3ace03)

**Comment by mikemcalister** [comment]
Hi there, thanks for reporting this. You _should_ be able to style this in the Global Styles panel by searching for the Next and Previous and changing the background. However, a core bug seems to be preventing the color from changing. 

As a workaround, you can choose a Gradient color, which will change the color, and then set both colors to the color you want. I made a quick video demonstrating. Hope that helps! 

https://github.com/OllieWP/ollie/assets/1415737/1a0adde5-c830-44bf-9044-b5cbd13bbbaa
