### ISSUE TITLE
Custom fonts not showing in the style guide

### ISSUE THREAD

**Issue by creativefibro** [OllieWP/ollie#59]
**Describe the bug**
Custom themes are showing on the website but not in the style guide.
**To Reproduce**
1. I originally installed Spectra One theme and the Custom Fonts Plugin.
2. I set the Custom fonts in the initial template.
3. I switched to the Ollie theme.

**Expected behavior**
4. When I go to the style book the Headers (H1 is especially noticeable) are not displaying as the correct font.
5. Then I look at the pages in the front end the correct custom font is showing correctly.

**Screenshots**
<img width="878" alt="Front End font showing correctly" src="https://github.com/OllieWP/ollie/assets/39191327/3f10267f-af04-4965-add1-155bcfc6a80b">
<img width="506" alt="Style Book showing incorrectly" src="https://github.com/OllieWP/ollie/assets/39191327/171b831b-b62a-4ec3-bf8d-919dd113149b">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Arc
 - Version 1.1.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mikemcalister** [comment]
Hi Susan, can you link me to the custom fonts plugin you're using? Block themes in general may not play well with that plugin because block themes have a specific way of adding custom fonts. Happy to take a look and see what the issue might be.

**Comment by creativefibro** [comment]
Sorry Mike,

I ended up swapping out the theme. I want to use the PostX plugin as I have the Pro and realised that they don't yet support FSE. When they do, hopefully soon (maybe in a matter of a week or two they say), I will move back to Ollie. I have since discovered how to add customer fonts through CSS rather than plugins so when I move back I hope this will be resolved.
Thanks
