### ISSUE TITLE
Absolutely love this theme & docs

### ISSUE THREAD

**Issue by EtchrUK** [OllieWP/ollie#60]
Hi, I'm working on a community interest company / not-for-profit and I'm using your theme. I've only just gotten started with blocks and FSE and you have hit the spot so many thanks. One thing I'd really like to do and that would have been using header.php or a plugin, and I don't want to use a plugin, and that is colourise the mobile with my brand colours. If you can point me in the right direction, or add it as a feature, because I've never seen that as a feature in a theme but it would be a cool one if you could hit a switch then put a hex value in then boom - browser colour like the bbc.co.uk website - I believe it can be done with Android and iOS.

Anyway, www.etchr.org.uk and what will be www.ecovibe.net are both works in progress. 

And one more thank you for all the lovely patterns, I'm looking forward to making some of my own. I'd be very happy to link back to you, I'm very much an open source advocate. Let me know if you are cool with that.

Peace!

**Comment by mikemcalister** [comment]
Hey @EtchrUK! Your sites are looking great so far, great job! Love seeing how folks are using the Ollie theme. We'll be putting this theme on WordPress.org soon, so it will be easy to update in the future. 

Can you give me a few more details about what you're trying to do on mobile? Which part do you want to colorize with your brand color? If you could send a screenshot, that would be really helpful. Happy to take a look and send you some ideas.
