### ISSUE TITLE
WordPress 6.3 breaks spacing between paragraphs

### ISSUE THREAD

**Issue by verquist** [OllieWP/ollie#61]
**Describe the bug**
Today my website auto-updated to WordPress 6.3. Now all of the spacing between paragraphs is removed.

Here is what my About page looked like under WordPress 6.2.2 + Ollie 0.3.

<img width="624" alt="WordPress 6 2 2 + Ollie 0 3" src="https://github.com/OllieWP/ollie/assets/8862114/47979f0c-cc29-419c-bfdc-9354abca8676">

Here is what my About page looks like under WordPress 6.3 + Ollie 0.3.

<img width="616" alt="WordPress 6 3 + Ollie 0 3" src="https://github.com/OllieWP/ollie/assets/8862114/92033e1b-4930-4539-8eab-7480b50cffcc">

**Workaround**
- Install plugin "WP Downgrade"
- Downgrade to WordPress 6.2.2

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser: All

**Smartphone (please complete the following information):**
 - Device: iPhone 
 - OS: iOS 16.5.1 (c)
 - Browser: Safari

**Additional context**
N/A

**Comment by mikemcalister** [comment]
Hi Jim, thanks for the note. That paragraph spacing should be fixed in the latest Ollie release here: https://github.com/OllieWP/ollie/releases/tag/0.1.4

We'll be submitting the theme to the WordPress.org repo soon, so updating should be a lot easier soon! Let me know if that release doesn't fix the issue. Looks good on my end!

**Comment by verquist** [comment]
Hi Mike, I should have known you had this fixed in your latest release before WordPress 6.3 hit. Good incentive for me to get my WordPress staging/testing process figured out and upgrade to Ollie 0.1.4.

Thank you!

**Comment by verquist** [comment]
Something is still not right.

I upgraded to Ollie 0.1.4. The paragraph spacing looks fine, except when a paragraph is followed by an image. Interestingly, the spacing looks fine in the block editor. But in preview mode or when viewing the website regularly (not via WordPress), there is no spacing between the paragraph and the top of the image.

Here's what it looks like in the block editor.
<img width="1440" alt="Block Editor-Ollie 0 1 4" src="https://github.com/OllieWP/ollie/assets/8862114/6d6def0d-b3aa-4660-a7be-bf8c484bb66e">

Here's what it looks like in page preview.
<img width="1440" alt="Page Preview-Ollie 0 1 4" src="https://github.com/OllieWP/ollie/assets/8862114/defff851-cf47-4719-b8d2-555126becad5">

**Comment by mikemcalister** [comment]
Hi Jim, 

Thanks for your patience on this one. I did make another update to the spacing a few days ago and it is in the latest release (which was released yesterday). Try that one out and let me know!
