### ISSUE TITLE
Glitchy from gallery block to columns and group block in option window

### ISSUE THREAD

**Issue by lada7042** [OllieWP/ollie#62]
**Describe the bug**
I was editing the home page. I set up a group>row>paragraph and gallery. Went to change the gallery block to a column or group and the screen became glitchy when trying to show the preview of these 2 blocks. . The image block option was fine with showing the preview. See video. 

**To Reproduce**

**Expected behavior**
A clear preview of what the column block or the group block options would look like. 

**Screenshots**
Video- https://github.com/OllieWP/ollie/assets/24979729/01fffb40-cd13-42b1-a3fa-42831ef05057

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  HP desktop 
 - Browser [e.g. chrome, safari]  Chrome dev. 
 - Version [e.g. 22]  22H2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mikemcalister** [comment]
Hi Laura! Could you try re-uploading the video of this issue? Looks like it didn't upload properly. Happy to take a look!

**Comment by lada7042** [comment]
Sorry about that- 

https://github.com/OllieWP/ollie/assets/24979729/c0c1a6d7-9ada-40b7-87aa-7e2b1cef30d4

**Comment by lada7042** [comment]
I wanted to update- The glitch was happening with the ollie-child file I had gotten from the BuildMode call. I deleted that and made my own child theme and the glitch is gone. Great job on the theme. Having fun designing with it.
