### ISSUE TITLE
Lost attempting to install

### ISSUE THREAD

**Issue by kaymac41** [OllieWP/ollie#63]
Ollie has sent me a blueprint file, and my eye is naturally drawn to ./ollie-local-blueprint/app/public/wp-admin. I expected to find a launch execution file in that directory that would have created a new instance of wordpress with ollie theme installed within it. Apparently I had it all wrong. Please advise how to get from here to there. I'm trying to prototype a new web site to replace the existing one, which at all costs must not be disturbed during prototyping.Oh, and I want to build the prototype using ollie theme.

Keith
keithgunn@mehermail.com
925-254-1791

**Comment by verquist** [comment]
Hey Keith,

1. Install a fresh version of WordPress on your testing/staging server
2. Download Ollie theme zip file (current version = 0.1.4)
3. Install Ollie theme into WordPress
4. Create your new website using Ollie theme
5. Once website is set up exactly the way you want, move the new WordPress install to your live server.

Mike is working on a nifty way to spin up a new WordPress site using Ollie, but it's not available in Ollie 0.1.4. => https://olliewp.com/in-pursuit-of-a-more-intuitive-onboarding-experience/

Cheers, Jim
