### ISSUE TITLE
When editing a page's template (starting from the page), Header and Footer template parts show "This block has encountered an error and cannot be previewed"

### ISSUE THREAD

**Issue by greening** [OllieWP/ollie#65]
**Describe the bug**
In Ollie 1.0, editing templates starting with editing a page displays "This block has encountered an error and cannot be previewed." instead of Header template part and Footer template part.

**To Reproduce**
1. Login as an admin
1. Create a page using standard Page template
1. Go to that page
2. Click "Edit Page" on top
3. Under the page tab on the sidebar, select what appears after "Template", which I think should be "Page".
4. It should say "Default template" in the dropdown menu
5. Underneath that, it should have a link "Edit template"
6. Click it
7. Note that instead of showing the content of Template Part "Header" and "Footer" on the page template, it shows "This block has encountered an error and cannot be previewed."

**Expected behavior**
It should show the contents of the Header and Footer template parts in step 7.

I tried this with the Frost theme, and it works as expected.

I originally implemented this with the Ollie 0.12 theme, and it works as expected there also.

**Screenshots**

<img width="1090" alt="Screenshot 2023-08-17 at 4 13 38 PM" src="https://github.com/OllieWP/ollie/assets/79808/4bfcbe41-f8ff-4889-9c86-0e1c349e1a13">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome

**Comment by mikemcalister** [comment]
Hey Dan, hard to tell from that error, but this may be related to an issue we had with the site logo. I just released a fix for that in version [1.0.1](https://github.com/OllieWP/ollie/releases/tag/1.0.1) a little bit ago.

If that doesn't fix it, do you mind copy/pasting the error in the console for me to take a look at? Thanks in advance!

**Comment by greening** [comment]
Fixed! Thanks.
