### ISSUE TITLE
Site logo php error?

### ISSUE THREAD

**Issue by ronsrac** [OllieWP/ollie#67]
After installing Ollie 1.0 I followed the installation wizard and uploaded my logo.
The logo however does not appear on the website.

I then checked the Wordpress installation on the server and it reported an corrupt installation:

![Screenshot 2023-08-21 16 22 26](https://github.com/OllieWP/ollie/assets/79981165/d12185b5-8250-4bdb-ba65-2eb55d5f3b95)

I then activated an another FSE theme Neve and the logo does appear.
I got back to the server and no problems where found.

Looking at the logs says the following:

![Screenshot 2023-08-21 16 31 16](https://github.com/OllieWP/ollie/assets/79981165/c5d2912b-aed0-471e-8c8a-ab92f15e5e96)

I worked on Chrome as well as Local.

**Comment by mikemcalister** [comment]
Thanks for the heads up! Taking a look at this now. We'll release a fix for it shortly.

**Comment by mikemcalister** [comment]
I've just pushed a fix for this in [v1.0.1](https://github.com/OllieWP/ollie/releases/tag/1.0.1). Let me know if you have any other issues!
