### ISSUE TITLE
Problems with showing right homepage

### ISSUE THREAD

**Issue by bfossan** [OllieWP/ollie#68]
**Describe the bug**
I have made a set of pages, went into core wp, and chose the new "homepage" as a static page. When I click the menu, your theme homepage still shows, but when I click to work with it, it is back to my own made homepage. Seems that the system thinks that your theme homepage and my homepage are the same, but shows your theme front and my own page backend.

**To Reproduce**
I can not.

**Expected behavior**
After making a new homepage/frontpage, and choosing that page as a static page, I expected to see the homepage I made, not the themes dummy content.

**Screenshots**

**Desktop (please complete the following information):**
 - Mac OS Ventura
 - Chrome, last version.

**Additional context**
Please advice, is it a bug, or am I missing something?

**Comment by mikemcalister** [comment]
Hi there, which version of the theme are you using? Older versions of the theme used a Front Page template, and that overrides the home/blog static page. 

Go into Appearance → Editor → Templates and see if you have a Front Page, if so you can delete that and it should show the pages you selected instead.

**Comment by bfossan** [comment]
I use Versjon: 0.1.1

I do work with it locally on my Mac (local by Flywheel).

How do I remove the template front page? Seem to not get to do that as a choice in any setting. Is there a directory in the installation I can remove it?

Hope I get to solve my little predicament, not sure if it is a bug, or I`m having my head up a place where the sun never shines...

Thank you for a brilliant theme, by the way!

Bent Fossan
Adresse/Adress:
Vearåsen 48
N-3173 Vear
Norway
Telefon/Phone:
+47 90 60 38 03

**Comment by mikemcalister** [comment]
Apologies for the delay. You can go into `Appearance → Editor → Templates` and if you have a Front Page and have an option to delete it, you know the theme is using that instead of what's in the theme.
