### ISSUE TITLE
No "Replace Header" option, cannot upload logo, color change problem

### ISSUE THREAD

**Issue by simona123R** [OllieWP/ollie#69]
I don't see Replace Header or Replace Footer options in the Header and Footer choices. 
![replace header missing](https://github.com/OllieWP/ollie/assets/142829403/e8acba39-b712-4d27-88fc-66bd2b104c5c)

I'm also not sure how to change the colors of individual sections, as, for example, if I change the header color to white, the footer gets the same color too. How do I individually select the colors for them? Thank you.

**Comment by simona123R** [comment]
![Screenshot 2023-08-21 225342](https://github.com/OllieWP/ollie/assets/142829403/71679c27-02b2-4302-bbc6-6d29e732e195)
I'm also attaching the logo dashboard.

**Comment by mikemcalister** [comment]
Hi @simona123R! This seems to be a core bug. I saw someone mention this in the official WP repo. So hopefully we get a fix for that soon. I've seen it myself, and sometimes just clicking around (on and off the element) can help. You might also try the layer view, that could help.
