### ISSUE TITLE
Confusing website, then failed to install

### ISSUE THREAD

**Issue by futuressobright** [OllieWP/ollie#70]
**Describe the bug**

Within cPanel/Wordpress:

[ Tried to install twice Error message but and pasted below.]

Installing plugin from uploaded file: ollie-main.zip
Unpacking the package…
Installing the plugin…
The package could not be installed. No valid plugins were found.
Plugin installation failed.

**To Reproduce**
Download the Zip file and attempt to install it.

**Expected behavior**
Install the Wordpress plugin!

**Comment by mikemcalister** [comment]
This is not a WordPress plugin. This is a WordPress theme. To use it, you would need to install the Ollie.zip file found in the [latest release](https://github.com/OllieWP/ollie/releases/tag/1.0.0).
