### ISSUE TITLE
homepage header background video

### ISSUE THREAD

**Issue by salsero72** [OllieWP/ollie#71]
Hi 
great theme with many beautyfull formatted patterns!
I am wondering how to add background video like demo.olliewp.com (girl on couch)
I can't find how to in the docs and no proper fields in the block settings.
I used an external plugin but am not completely satisfied with that and wondering if there is an in-theme setting I am missing.

I used: "Video background" from https://wordpress.org/plugins/b-blocks/

Thanks!

**Comment by mikemcalister** [comment]
Hi there, 

Apologies for the delay! Video is added by using the Cover block. It will let you use an image or a video as the background. And then you can adjust the opacity of the image by sliding the Overlay setting up and down. Hope that helps!

**Comment by salsero72** [comment]
Thank you!
