### ISSUE TITLE
Brand Color

### ISSUE THREAD

**Issue by krstivoja** [OllieWP/ollie#73]
Why brand color can not be choosen from the curent palette?

Atm you need to add custom hex but that will not by synced

<img width="1087" alt="Screenshot 2023-08-30 at 19 24 00" src="https://github.com/OllieWP/ollie/assets/1234350/b62dd73d-b1d6-4089-a007-ee384cc01960">

**Comment by mikemcalister** [comment]
The idea here is that you choose a color palette that is close to your brand colors. Then, you choose your exact brand color, which will override the main accent color in the color palette (in this case, it would override the green color). So in effect, it's adding the brand color to the color palette, and will be available to use in the editor.
