### ISSUE TITLE
Header Navigation Block Spacing Not Showing on Front-end

### ISSUE THREAD

**Issue by eliehanna0** [OllieWP/ollie#74]
**Describe the bug**
Applying any block spacing value to the Navigation Block in the header does not seem to work on the front-end, although the spacing is applied while in the block editor.

**To Reproduce**
1. Go to Appearance -> Editor
2. Search for "Header" and click on it
![image](https://github.com/OllieWP/ollie/assets/76950619/728caa75-9b4f-43bf-859b-c1c177374f2f)
3. Click on Edit
![image](https://github.com/OllieWP/ollie/assets/76950619/5cbaa8c9-87b6-4169-ae76-8b2be6d886ba)

4. Add a new Navigation Block inside the header
5. Select Navigation Block, go to the styles tab and mess around with the block spacing

**Expected behavior**
Correct navigation block spacing should show on the front-end.

**Screenshots**
2.1 REM spacing applied to the Navigation Block on the block editor.
![image](https://github.com/OllieWP/ollie/assets/76950619/ff57607b-afc0-4cb0-9366-d06d1e529062)

Front-end, Nav Block is not reflecting the applied block spacing
![image](https://github.com/OllieWP/ollie/assets/76950619/728caa75-9b4f-43bf-859b-c1c177374f2f)

 - OS: Win 10
 - Browser Chrome
 - Version 116.0.5845.111 (Official Build) (64-bit)

**Comment by mikemcalister** [comment]
Hi there, 

Unfortunately, this looks like a core bug. I've switched to two other themes and the block spacing seems to be not working there as well. I'll keep an eye out for a fix!

**Comment by mikemcalister** [comment]
On a closer look, I may have found a fix! I'll push up an update shortly with this.

**Comment by mikemcalister** [comment]
I've just [pushed a fix](https://github.com/OllieWP/ollie/commit/f2e5488352430ce6e7ccbd45e6eedd38fdc362f8) to the `develop` branch. This will be in the next proper release, but for now, you can grab the fix from `develop`.
