### ISSUE TITLE
Theme not Working After Migration

### ISSUE THREAD

**Issue by ebenstars** [OllieWP/ollie#75]
Hello,

We have recently created a site around this Ollie theme and migrate it to another VPS. While it looks fine at its original origin, the navbar and "Cover" blocks are not displaying correctly at new location on VPS. All domain are correct after migrate and in the editor it looks correct too after migration just not displaying correctly live.

Can you please help us?

Old location looking fine: [https://carnivalweekly.com/]

New location looking janky?: [https://carnivalsupermarkets.com/carnival-chula-vista/](url)

Thank you.

<img width="2093" alt="Screenshot 2023-09-01 at 3 12 41 PM" src="https://github.com/OllieWP/ollie/assets/130090604/9d3b4c00-03f0-408e-8e72-92e99940bc87">
<img width="1756" alt="Screenshot 2023-09-01 at 3 12 55 PM" src="https://github.com/OllieWP/ollie/assets/130090604/104d108d-4dd9-4f81-8ec6-77b52b329eb5">

**Comment by mikemcalister** [comment]
Hi there, 

This is actually a core bug, unfortunately. I ran into it on my own sites over the past few days. Luckily, it is being actively worked on and you can [follow the progress here](https://core.trac.wordpress.org/ticket/59111). 

The workaround I was given was to add this to your wp-config.php file: 

`define( 'WP_DEVELOPMENT_MODE', 'core' );`

Hopefully that helps!

**Comment by ebenstars** [comment]
Thank you for your response, it is appreciated. I wish this wasn't the case, since my client is waiting for this and I need to pay rent :(


I tried the work around and this happened:
<img width="2535" alt="Screenshot 2023-09-01 at 3 18 50 PM" src="https://github.com/OllieWP/ollie/assets/130090604/ff2a735d-3b36-474d-8a47-691feb561d68">

Kind regards,

Erik

**Comment by mikemcalister** [comment]
All of those errors seem to be coming from the migration plugin. If you're done migrating, you might try turning that off.

**Comment by ebenstars** [comment]
Thanks again for getting back to me. Yes, I realized that and did exactly as you mentioned. Am I safe using that line of code you shared for now? It seems to have fixed it.

Regards,

Erik

**Comment by mikemcalister** [comment]
Yeah you should be ok using that for the time being. I would just keep an eye on the site in case any other plugins are outputting errors. Not sure if it's related to that line of code or not, but just to be safe. There should be a fix coming soon for that.

**Comment by ebenstars** [comment]
Okay thank you so much. Can you hit me up when the actual fix comes?

Thank you,


Erik
