### ISSUE TITLE
margin-block-start issue (?)

### ISSUE THREAD

**Issue by tiborp** [OllieWP/ollie#77]
Hi Mike,

First of all: thanks for sharing this inspiring project! I'm playing with it now and have already learned a lot from it. I ran into an issue though:

Using the `Page (no title) ` template, the first block I use on the page (a Cover Block in this case) has no margin on top (nor bottom), which is what I expect. But when adding more blocks, all those blocks have a top margin, apparently through this CSS:
```
:where(body .is-layout-constrained) > * {
    margin-block-start: var(--wp--preset--spacing--medium);
    margin-block-end: 0;
}
```
How would I avoid having those margins? Or better: how/where are they defined? I noticed that in the `page-no-title.html` there is a line `<!-- wp:post-content {"layout":{"type":"constrained"}} /-->`, but changing that into something else does not seem to have any effect?

Thanks in advance!

**Comment by tiborp** [comment]
Never mind: I found the margin settings for the block can be set to 0 (wasn't very intuitive at first).

**Comment by mikemcalister** [comment]
Hi Tibor, sorry for the delay. Yup, you can just adjust the margin as need per block. Groups get a top margin by default, and sometimes that can interfere with a design, so I just set the top/bottom to 0.
