### ISSUE TITLE
Google fonts not appearing for selection in block

### ISSUE THREAD

**Issue by rottinger** [OllieWP/ollie#80]
**Describe the bug**
I am Ollie to re-design our church's website.  I have several custom patterns I use, and couple of which use Google fonts ("Shadows Into Light Two" and "Pacifico").  I've installed the "Create Block Theme", and I'm using the "Manage Theme Fonts".  I have selected the fonts I want to use (I'm in the US, so I am just using Google fonts and not uploading font files on the site).  I've looked at the theme.json file, and all of the fonts are registered.

When I add a block to a page (in this case a paragraph block), add my text, and then go to the styles section to select the font I want to use, I only see a list of six fonts that show up, which doesn't include the one I want to use.

**To Reproduce**
1. Select block or page to edit.
2. Add or select paragraph and add text.
3. Click on "Styles".
4. Under "Typography", select "Font Family".
5. Select drop list.
6. Displayed fonts are Default, Inter, Monospace, Raleway, Poppins, Shadows Into Light Two.
7. Fonts not displayed are Pacifico and Merriweather

**Expected behavior**
I would expect that the drop-down list would include any fonts that I have installed for use in the site.

**Screenshots**
![image](https://github.com/OllieWP/ollie/assets/44176823/e0dc739e-8c98-4d7c-b5c5-7cb08a076062)
[theme.json.txt](https://github.com/OllieWP/ollie/files/12599650/theme.json.txt)

**Desktop (please complete the following information):**
 - OS:  Windows 11 22H2, version 22621.2283
 - Browser:  Firefox, version 117.01 (64-bit)
 - WordPress 6.3.1

**Comment by mikemcalister** [comment]
Hi Ronald, thanks for writing in. This one is a bit hard to reproduce on my end without the full theme. Could you export your theme and send it over and I'll take a look? You can export it by going into the site editor, clicking into the site, and using the menu in the upper right, as seen below: 

<img width="781" alt="Screenshot 2023-09-13 at 11 50 37 AM" src="https://github.com/OllieWP/ollie/assets/1415737/4b6e875b-e4a4-4255-9a4a-9e0844a7c224">

**Comment by rottinger** [comment]
Mike,

Thanks for the quick reply.  Here's the export.
[modified-ollie-main.zip](https://github.com/OllieWP/ollie/files/12600110/modified-ollie-main.zip)

**Comment by rottinger** [comment]
Mike,

I think you don't have to do anything.  I had to step away from working on the site for a bit, and when I went back in, I could select any of the fonts I have loaded.  I don't have caching on the site (this is a local development version I'm working on), so I can't explain it.  But it looks like the font selection is working as it should.  Sorry about that.

Just BTW, I am "really" liking Ollie.  Our site is small, and I'm the only one that maintains it, and I'm into minimizing as much as I can.  For our purposes, I'm trying to go straight Gutenberg and a good block theme, and Ollie has been checking all the boxes.  Thanks!

**Comment by mikemcalister** [comment]
Glad to hear it, Ronald! The theme will be available on WordPress.org very soon! That means you'll be able to easily install and update it right from within WordPress. We've also got some really nice additions and improvements that will come with the official release. 

Thanks for the update!

**Comment by idrosua** [comment]
Hi @mikemcalister, I have built a simple custom font plugin that can be use on Gutenberg editor.
Perhaps do you have a vision on the theme wizard on customizing the font that we can collaborate?

my simple plugin available on WP directory under the name "Yabe Webfont" (or GitHub [repo](https://github.com/orgrosua/yabe-webfont))
