### ISSUE TITLE
Template created for a category is using a post's title in the title field

### ISSUE THREAD

**Issue by creativefibro** [OllieWP/ollie#81]
**Describe the bug**
I have just created a template to be used for a specific category. I used the Title block in it. When viewed at the front end instead of giving the title of the category it gives the title of the most recent post within the category.

**To Reproduce**
Created a new template
Used the title block without altering it.
Added the rest of the content to the template.
Viewed it at the front end.

**Expected behavior**
I expected the title to read the name of the category it was created for rather than a blog post title.

**Screenshots**
The screenshots show the back end view, the browser tab showing the category I expected to see (Fibromyalgia) and the front end displaying the title of the last blog post.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Arc (Chromium)
 - Version: 1.7.0 

**Smartphone (please complete the following information):**

**Additional context**
<img width="1703" alt="CleanShot 2023-09-14 at 12 04 48@2x" src="https://github.com/OllieWP/ollie/assets/39191327/a596b924-f19a-487b-9984-8cb4c879a1af">
<img width="164" alt="CleanShot 2023-09-14 at 12 05 13@2x" src="https://github.com/OllieWP/ollie/assets/39191327/d5eda27c-21b1-4c05-a55c-cc834665de91">
<img width="1274" alt="CleanShot 2023-09-14 at 12 05 29@2x" src="https://github.com/OllieWP/ollie/assets/39191327/26a4ca11-1614-496c-baed-99ae0a77d9d0">

**Comment by Ren2049** [comment]
Hey, try the Archive Title Block: https://wordpress.org/documentation/article/archive-title-block/

**Comment by creativefibro** [comment]
Thanks Ren

**Comment by creativefibro** [comment]
Resolved now thanks
