### ISSUE TITLE
child theme

### ISSUE THREAD

**Issue by pikabon63** [OllieWP/ollie#82]
Hello, 
I'd like to use the Ollie theme for an association website. I have a question: if I modify the json file of the Ollie theme and save the modifications with create block theme, won't I have to worry about updating the theme in the future? Will all changes be preserved? Or do I have to create a child theme? The problem is that I don't know how to create a child theme of an FSE theme? Is it any different from the classic method (non FSE theme)?
thanks for your help
Best regards
Alexis

**Comment by VFlame44** [comment]
Hey Alexis,

Mike or others can add responses here, but I will give you some feedback …

To protect yourself from future theme updates (as you mentioned), YES, it is best to use a Child Theme.  Or yes, when you do an Ollie theme update down the road, the main theme files will be overwritten.

To create a Child Theme for a FSE (Block) Theme, I think there are 4 good ways to do this:
1)  Start with the Child Theme that Mike provides in GitHub
     ○ https://github.com/OllieWP/ollie/releases/tag/1.0.1

2)  Generate a Child from Mike’s “Ollie setup wizard”
   ○ The Child Theme creation is done in the “Finish step”, wizard is kicked off when you activate the Ollie theme.
   ○ If Ollie ((v1.0.1) is already installed, you can access wizard in WordPress panel:
            Go To  >  Appearance  >  Ollie  >  Theme Setup  >  Finish  >  “Create Child Theme”

3)  Use “Create Block Theme” plugin to create Child

4)  Create Child file structure on your own, Zip it up, then upload it as your Child.

A FSE Child theme (ollie-child) structure, can be as simple as
------------------------------------------------------
readme.txt
screenshot.png
style.css
theme.json


After you have your Child theme, yes, that is where you want to make your “theme.json” modifications (in general, do whole sections at a time, to override Main theme.json settings).  In your child, you can also create additional global styles (for color schemes), which will be located in your “styles” folder.  There are other customizations you will find out you can put in your Child, as needed.

Some references for Block/FSE child themes are …
○ https://developer.wordpress.org/themes/advanced-topics/child-themes/
○ https://fullsiteediting.com/lessons/child-themes/
○ https://wordpress.org/plugins/create-block-theme/

Classic vs. FSE, to me child themes for FSE seem easier.  But there is a lot more granular control that you have over FSE/Block themes, so there is a lot you can do to customize & also a lot that you can learn to do.

**Comment by pikabon63** [comment]
Hi Larry, 
thank you so much for your answer. Just perfect. I've started with the Child Theme that Mike provides in GitHub and begin to make my own theme.json. 
thank you also for the very instructive links
I think I'm going to love FSE
Best regards
Alexis

**Comment by pikabon63** [comment]
hi, 
Hello, 
it's weird, when I add a custom color to the default palette in the json of my child theme and save with the save button. The custom color appears in my color palette. But if I go to Create block theme > Save changes, the color is written in the child theme's theme.json file, but it's disappeared from the color palette... 
Is there an explanation?
thanks
best regards

**Comment by VFlame44** [comment]
Hi! ...  Ok, I think I know where you are.

I’ll explain a few more things to you, I think you will catch on fast!

For getting through this quickly, I’m just going to make a bunch of statements …

- 	If in WordPress admin, you go to  >  Appearance  >  Editor  >  Styles  >  you will see color blocks for the Default Color Palette & Blocks for all the Color Style variations (you can mouse over them and a name will show up)
- 	The “Default” color palette (this one is the color palette in Main Ollie theme, in theme.json)
- 	The other palettes are Style/Color Variations - these live in the “styles” folder of both the Main & Child themes
- 	Mike has a number of Style Variations that come with Ollie (that are in the Main Ollie theme “styles” folder)
- 	You can add a “styles” folder to your Child, and then add as many .json files as you want for different color palettes.
- 	Look in the main Ollie theme “styles” folder to see Mikes.
- 	Then make 1 or more of your own, for your Child theme.
--------------------
- 	If you do add a Style Variation in the Child theme … then you want to go into
- 	Appearance  >  Editor  >  Styles  >  and select your Variation (look for the unique name you gave it in the Title, mouse over to see the names)
- 	When you Select it, you will see a Border around the color palette box, and then all the color variables will be set to use your Color Palette

Here is the contents of one of my style/color variations (“blue-green.json” file in “styles” folder of Child theme).  I flatten the file code out for my easy readability. 
![2023-09-15_184920](https://github.com/OllieWP/ollie/assets/129994813/84266641-0d1a-4713-abcd-691b1f92fdbb)

Here is the "styles" folder in the Main & Child themes.

![2023-09-15_185224](https://github.com/OllieWP/ollie/assets/129994813/50546a24-838b-4410-996e-b202969fada9)

![2023-09-15_185148](https://github.com/OllieWP/ollie/assets/129994813/bf8a8a5a-9743-42bf-80d2-62103cd96e5f)

Getting back to what you were seeing/experiencing …
•	I’m not sure in which way you added the custom color to the palette, but here is how it works in general.
•	When you do make changes to things in WordPress admin, those changes are stored in the database (separate from the theme or child files).
•	If you have a Child, and then you do a Save with Create block theme, the database changes are written to you Child theme files. (and that might be why it looks as though it disappeared.)
•	If you do create a Global Style Variation (for your color palette), and put it in your Child's "styles" folder  >  then select your Color palette (vs. the Default)  >  All of your colors will be used.

Here is a Link to help put things in context some … but it doesn’t go into detail on the Child theme.
https://wpengine.com/builders/child-themes-style-variations/

Hope it helps

**Comment by mikemcalister** [comment]
Thanks so much for hopping in and helping out, @VFlame44! I've been working non-stop on getting the theme through the review for WordPress.org. Should be available very soon! 

@pikabon63, what Larry has provided here is exactly what I would advise, hopefully that clears it up! Child themes are a bit tricky to get the hang of.

**Comment by pikabon63** [comment]
Hi Larry
Thanks a lot for your great assistance👏🏻
I think I will have others questions later 😉
Best regards 
Alexis
