### ISSUE TITLE
Ollie Theme Popup Stuck on screen

### ISSUE THREAD

**Issue by mbelmar05** [OllieWP/ollie#83]
**Describe the bug**
I have installed the Ollie theme on a localhost server in linux.
Once the theme is installed, there is a welcome to Ollie popup that doesn't go away. It gets stuck on the themes panel.
(image attached)

**To Reproduce**
1. Go to thems, upload Ollie zip file to install new theme
2. Once installed, Welcome popup shows up
3. Click on the closing cross or "View Ollie Dashboard" or "Skip for now"
4. The popup does not close.
5. Go to wordpress admin, come back to themes, pop up still there

**Expected behavior**
Popup should close

**Screenshots**
If applicable, add screenshots to help explain your problem.![Ollie-popup-error](https://github.com/OllieWP/ollie/assets/145059633/c9b822d6-4cf2-47bb-aedc-d8f5f7eb6f09)
**Desktop (please complete the following information):**
 - OS: Linux Mint 21.1 Vera
 - Browser Chrome 
 - Versión 117.0.5938.62 (64 bits)

**Comment by mikemcalister** [comment]
Hi there, this should be fixed in the latest version of the theme, 1.0.3, which was released yesterday. Try installing that version and let me know if you see any other issues.
