### ISSUE TITLE
The dashicons bloat seems unnecessary 

### ISSUE THREAD

**Issue by kauaicreative** [OllieWP/ollie#84]
Awesome theme - loving what you are doing!

Google page speed score was complaining about dashicons - the extra bloat seems unnecessar.
Perhaps just use ascii  ✔  ✓ 

```
function enqueue_block_dashicons() {
	wp_enqueue_style( 'dashicons' );
}
add_action( 'enqueue_block_assets',  __NAMESPACE__ . '\enqueue_block_dashicons' );
```

**Comment by mikemcalister** [comment]
Hey Sunny, thanks for the feedback. I agree, and I'm working on a way to only load that when a block calls for it. Should have something available for that shortly.

**Comment by mikemcalister** [comment]
Dashicons has been removed in one of the recent updates. No more dashicon bloat!

**Comment by wgordon17** [comment]
@mikemcalister this seems like a pretty massive and breaking change for anyone that might have been relying on Dashicons (like myself)! There's nothing in the [releases changelog](https://github.com/OllieWP/ollie/releases) that addresses this. Perhaps it would been a better and safer change to make this an opt-out option, versus just nuking it for everyone ¯\\\_(ツ)_/¯
