### ISSUE TITLE
Post excerpt settings

### ISSUE THREAD

**Issue by rottinger** [OllieWP/ollie#86]
**Describe the bug**
When selecting a post query pattern (specifically a post query grid), I am unable to change the max number of words for the excerpt length.

**To Reproduce**
1. Go to a page.
2. Toggle block inserter.
3. Select "Patterns", "Posts".
4. Select "Post Loop Grid".
5. Expand the "Query Loop", and navigate down to the "Excerpt" block.
6. Under "Block Settings", change the "Max Number of Words".

**Expected behavior**
I would expect that the max number of words to display in the excerpt would change based on the settings.  But it appears there is an additional CSS class assigned under "Advanced" that, by default, limits the display to two (2) lines.  A look at the style sheet for "core-post-excerpt.css" shows default styles set as follows:

.is-style-excerpt-truncate-2,
.is-style-excerpt-truncate-2 .wp-block-post-excerpt__excerpt {
	-webkit-line-clamp: 2;
}

.is-style-excerpt-truncate-3,
.is-style-excerpt-truncate-3 .wp-block-post-excerpt__excerpt {
	-webkit-line-clamp: 3;
}

.is-style-excerpt-truncate-4,
.is-style-excerpt-truncate-4 .wp-block-post-excerpt__excerpt {
	-webkit-line-clamp: 4;
}

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro, 22H2
 - Browser Firefox, ver. 117.01 (64-bit)

**Additional context**
If I remove the advanced CSS class, I am able to set the number of words to display in the post excerpt.  If the user is to be allowed to set the excerpt length, maybe there could be another setting to set the CSS style to set how many lines, versus how many words, to display.

**Comment by mikemcalister** [comment]
Hi Ronald, this should be a quick fix. When you have the Excerpt block selected, click the block settings and make sure Default is selected in the Styles panel. This will let the excerpt show whatever number of words you want. 

<img width="508" alt="Screenshot 2023-09-20 at 8 07 34 PM" src="https://github.com/OllieWP/ollie/assets/1415737/c90d2586-004f-4fc0-9c69-c84bef8d878a">

**Comment by rottinger** [comment]
Looking right at it and missed it.  Thanks, Mike!
