### ISSUE TITLE
No CSS is being rendered on a fresh install

### ISSUE THREAD

**Issue by filip-van-hoeckel** [OllieWP/ollie#87]
**Describe the bug**
We installed the theme and started work on the backend. However no CSS is being rendered whatsoever.

**To Reproduce**
In our case: install, then get to work

**Expected behavior**
The FSE editor renders just fine; it's when viewing the frontend like there's no CSS whatsoever.

**Screenshots**
https://i.imgur.com/WwkGqjS.png

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: Latest

Applying a default theme, then swapping back did not work. Changing the global styles did not work either. Please advise, thanks.

**Comment by mikemcalister** [comment]
Hi there, I can't replicate this on my end. I've tested on a few different installs and the editor and styles render fine. Are you using the latest version of the theme that was released yesterday? I would maybe delete the theme and reinstall.

**Comment by filip-van-hoeckel** [comment]
Found that it conflicts with https://github.com/vinkla/headache probably the Gutenberg parts in that. Thanks.
