### ISSUE TITLE
No Ollie Dashboard after updating from 1.01 to 1.03

### ISSUE THREAD

**Issue by Leemshop** [OllieWP/ollie#88]
**Describe the bug**
After updating 1.01 tot 1.03 the Ollie Dashboard is no longer available through https://olliewp.leemshop.nl/wp-admin/themes.php?page=ollie

**To Reproduce**
1. Go to 'Github tot download the fresh update'
2. Upload the 1.03 in the WP admin Appearance/Themes/Upload
3. Replace the old version for the new one
4. Verything OK, but no acces to Ollie Dashboard

**Expected behavior**
I expected acces to the Ollie Dashboard

**Screenshots**

**Desktop (please complete the following information):**
 - Debian Linux : [e.g. iOS]
 - Brave Browser [e.g. chrome, safari]
 - [Versie 1.58.131 Chromium: 117.0.5938.92 (Officiële build) (64-bits)](https://brave.com/latest/) [e.g. 22]

**Smartphone (please complete the following information):**

**Additional context**
A childtheme from OllieWP was installed

**Comment by mikemcalister** [comment]
Hi there, 

Is this still happening if you update to the latest version of the theme ([1.0.4](https://github.com/OllieWP/ollie/releases/tag/1.0.4))?

**Comment by Leemshop** [comment]
Hi Mike,
1.0.4 makes it work again!
Kind regards
Geert
