### ISSUE TITLE
template parts not visible in some Templates

### ISSUE THREAD

**Issue by salsero72** [OllieWP/ollie#89]
**Describe the bug**
In Product Category Page Template I added "Header" and "sidebar", but they are not shown.
In html I find the container column but it's empty (no html)

**To Reproduce**
1. Go to Editor -> Templates -> Products By Category -> Edit
2. Somewhere in the page add  Template parts (I tried header and sidebar)
3. Save and clear cache if any
4. No template part is shown, while other paragraphs are shown in the same column

**Expected behavior**
Sidebar or header should be in html and visible

To circumvent this I had to create custom patterns (customHeader and customSidebar)  (btw: I copied pasted the blocks from template parts)

I am NOT sure this is an issue from OllieWp. Probably is from my lack of knowledge of the FSE matter but I head-banged my third keyboard now :-|

To overcomplicate things: [shortcdes] do not work in patterns :-|

Thanks.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [clinet: Windows, Server Linux Centos ]
 - Browser [e.g. chrome/any]

**Comment by mikemcalister** [comment]
Hi there, 

Can you let me know what you're using to get the Products screens? Is this being used with Woo?

**Comment by salsero72** [comment]
Hi 
yes Woocommerce.  (products are not involved in header and sidebar though)
I can DM url and login credentials if needed.

**Comment by salsero72** [comment]
Hey I tried a new installation from scratch and both default sidebar (from Ollie) and my custom shortcode are showing and working as expected.
I'll investigate deeper on what is causing my issue.

Sorry for any extrawork!
N.D.

**Comment by mikemcalister** [comment]
No worries, thanks for reporting and updating!
