### ISSUE TITLE
New Ollie site performance issue

### ISSUE THREAD

**Issue by Ren2049** [OllieWP/ollie#90]
Hey Mike, 

Following the CTA about the new site in the email I've experienced a lot of almost unscollable jankyness in the hero area of the landing page. Scrolling past it it the jankyness disappears, scrolling back into the hero section the jankyness returns.

Browser: Mac Safari

**Comment by mikemcalister** [comment]
I'll take a look, thanks for the heads up!

**Comment by mikemcalister** [comment]
How's it look now? Should be a smoother scroll. You may need to clear your cache to see it.

**Comment by Ren2049** [comment]
Works well now, sorry for replying so late. I like the new font btw ;)
