### ISSUE TITLE
Improve on the favicon (site icon) handling

### ISSUE THREAD

**Issue by dingo-d** [OllieWP/ollie#91]
In the `add_favicon` callback

https://github.com/OllieWP/ollie/blob/4419caa5e620ea1c37f6b2fee21141f6874d41ef/inc/settings/inc/class-os-helper.php#L41-L49

you could enhance this functionality by using the code from [wp_site_icon](https://developer.wordpress.org/reference/functions/wp_site_icon/). You obviously cannot just use that function, as you're not in the customizer, but because of the GPL nature, you can just copy some parts of it.
If the site icon is uploaded through the media library you'll have multiple versions of it, and generate all the different sizes needed.

That way the favicon generation is a bit more robust, and closer to what WP core is doing.

BTW, really loving the onboarding experience, props for that, I hope something like this comes to the core, so that we can all benefit from it 🙂

**Comment by mikemcalister** [comment]
Thanks so much, Denis! We've actually removed the site icon feature (at least for now) while we work our way through the review at WordPress.org. Getting something like this in core is ideal, so hopefully we can get this approved and experiment with it and see what works.
