### ISSUE TITLE
Images in the header don't respect the height value

### ISSUE THREAD

**Issue by martingarnett01** [OllieWP/ollie#92]
**Describe the bug**
I've replaced the site title in the header template with an image. I've set the image height 32px.

Whilst editing the template, and viewing the published site, the image is perfect. However, when editing a page or page template, the image does not respect the 32px height.

**To Reproduce**
1. Go to the header tempalte
2. Delete the page title
3. Replace with an image (larger than 32px height)
4. Set a height (e.g. 32px)
5. Save template
6. Return to editing a page
7. Observe error

**Expected behavior**
The image in the header template should be the same wherever it's viewed.

**Screenshots**
Editing a page:
<img width="1344" alt="image" src="https://github.com/OllieWP/ollie/assets/9989080/854250d3-6df5-4c1e-bd8a-b6b29539af23">

Editing the header template:
<img width="1911" alt="image" src="https://github.com/OllieWP/ollie/assets/9989080/6d59f6c0-dbe7-468a-ba43-671f0300328e">

Image settings:
<img width="279" alt="image" src="https://github.com/OllieWP/ollie/assets/9989080/fc4dd2d7-be35-49bd-a80b-9eac00c11a6c">

Image styles:
<img width="280" alt="image" src="https://github.com/OllieWP/ollie/assets/9989080/3a1cfc20-7a37-4f89-ad1e-404dba1f8cca">

**Desktop (please complete the following information):**
 - OS: MacOS Ventura Version 13.5.2 (22G91)
 - Browser Chrome
 - Version 117.0.5938.132 (Official Build) (arm64)

**Additional context**
NA

**Comment by martingarnett01** [comment]
I didn't realise you can set a "Site logo" instead of an "Image" (still getting used to all the different types of blocks).

The Site logo block seems to work a lot better (although only appears to have a "Image width" control, which seems a little bizarre in a navbar).

Anyway, this is obviously a very low-priority, edge case bug but I wanted to log it anyway. :)

**Comment by mikemcalister** [comment]
Hey @martingarnett01, thanks for reporting this! I did a little deep dive, and I was able to reproduce this. 

Good news, this is fixed in the 6.4 beta 2. So we won't have to do anything here but wait a few weeks for a fix. 😎
