### ISSUE TITLE
Ollie homepage is broken on Safari (Mac OS)

### ISSUE THREAD

**Issue by verquist** [OllieWP/ollie#93]
**Describe the bug**
Images are not loading properly on Safari on my MacBook Pro (MacOS Catalina 10.15.7). Works fine on Firefox and Chrome. Works fine on my iPhone using Safari.

**To Reproduce**
1. Go to 'https://olliewp.com'
4. See funky homepage due to images not loading properly.

**Screenshots**
<img width="653" alt="OllieWP Homepage 2023-10-04" src="https://github.com/OllieWP/ollie/assets/8862114/093f4b48-14d6-4e38-baca-7352d6cf6294">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.
 - Browser: Safari

**Smartphone (please complete the following information):**
 - Device: iPhone 12 mini
 - OS: 16.6.1
 - Browser Safari

**Comment by mindctrl** [comment]
Seems to work on Safari 16.6 on macOS Ventura 13.6.x

<img width="1835" alt="image" src="https://github.com/OllieWP/ollie/assets/1254870/825d5fa2-7d0a-41b0-a24a-f3f9202266b3">

**Comment by verquist** [comment]
Rebooted. Still not loading images properly on MacOS Catalina 10.15.7. As I said, it works fine on my iPhone. Must be something specific to MacOS Catalina, or pre-MacOS Ventura 13.6.x anyway.

**Comment by Ren2049** [comment]
Is the current Safari 16.6 even available for Catalina? There were a lot of changes between the current one and the 15.x versions. If you're stuck on an older machine consider [OpenCore-Legacy-Patcher](https://github.com/dortania/OpenCore-Legacy-Patcher).

**Comment by mikemcalister** [comment]
Hey @verquist, thanks for the heads up. I've tried this on a few of my setups with Safari, but not seeing it yet. Please do ping us if you find any kind of clues here.

**Comment by verquist** [comment]
Hey @Ren2049, Good to know about [OpenCore-Legacy-Patcher](https://github.com/dortania/OpenCore-Legacy-Patcher).

I am running Safari 15.6.1 on MacOS Catalina 10.15.7.  One of the reasons I like running an older machine / operating system is to ensure things don't break as new software is released. (WordPress / Ollie). MacOS 10.15.7 was released 2 years ago, so ideally WordPress + Ollie should still work.

Something broke when Mike updated the Ollie website a few weeks ago. Previously it worked just fine on my setup. Not sure what broke it.

**Comment by mikemcalister** [comment]
I do have some caching enabled on there, but it's been flushed at the site level. However, I have had trouble in the past with Safari not flushing the cache. Have you tried it on private browsing in Safari?

**Comment by verquist** [comment]
Hey @mikemcalister, I had high hopes. Unfortunately, the problem persists even with private browsing on Safari.

**Comment by Ren2049** [comment]
@verquist Yeah, updating every year is odd, I try to stay on the same version as long as it gets securtity updates and doesn't exclude me from running the apps I need. 

If you can't upgrade best use a different default browser until you can, Safari 15.x isn't safe unfortunately.

**Comment by verquist** [comment]
Hi Mike, I think I found the answer. Did you switch to using [WebP images](https://en.wikipedia.org/wiki/WebP)?

Apparently [WebP isn't supported by Safari on Catalina](https://www.reddit.com/r/MacOS/comments/13ti3bb/i_have_a_problem_with_loading_pictures_in_safari/).
