### ISSUE TITLE
Global Custom CSS

### ISSUE THREAD

**Issue by gregoryfu** [OllieWP/ollie#94]
The ability to add CSS classes to block elements does not result in rendering on the back-end while you are editing, and requires a separate file for the CSS rules. The Twenty Twenty Four theme has a global custom CSS capability, letting you specify the selectors, and which does render instantly on the back end while editing, and on the front end. I would love to see this in Ollie.

**Comment by pmmueller** [comment]
May be I don't understand your wish the way you meant it, but the »global custom CSS capability« is built into the Site Editor and therefore available to every block theme (not just Twenty Twenty-Four): 

1. Open the (Global) `Styles` panel in the Site Editor and click on the `More` 3-dot-menu. 
2. Click on `Additional CSS`. 
3. Enter your CSS into the textarea. 
4. The Site Editor shows a live preview. 

![image](https://github.com/OllieWP/ollie/assets/1928205/196df0a1-50ad-46c3-8c03-7be845230b36)

In addition to the global additional CSS you can also add Additional CSS to every individual block. 

Or does your wish to refer to something else?

**Comment by gregoryfu** [comment]
You are right. Sorry I missed it, and thanks for a great theme. Closing this issue.
