### ISSUE TITLE
Improvement for Pattern »Feature Boxes with Icon« 

### ISSUE THREAD

**Issue by pmmueller** [OllieWP/ollie#95]
## Problem: Alignment of Read More link  
The pattern Feature Boxes with Icon has six cards with Columns containing a grouped Heading and Paragraph and a grouped Separator and a Row containing a Paragraph with Read More link and an icon next to it. 

The position of the grouped Read More link and its icon depends on the length of the text above it. With a short text the group moves up. 

Screenshot is in German, but you'll get the idea: 
![image](https://github.com/OllieWP/ollie/assets/1928205/08a1e5ce-81cc-45b5-a381-21606c4a9429)

- Spalten = Columns 
- Spalte = Column 
- Gruppe = Group 

## Solution: Add a stack block 
It would look nicer if the Read More link and its icon would always be positioned at the bottom of the column, no matter how much text the paragraph above contains. 

This is easily possible If the two groups are contained in a Stack block with `min-height: 100%`, vertical alignment with  `Space between` **and** horizontal alignment with `Stretch Items`. 

The group with the Read More link is then pushed to the bottom of the Stack block, which due to the min-height of 100% looks like the bottom of the Column block (see screenshot). 
 
![image](https://github.com/OllieWP/ollie/assets/1928205/6d9975f3-f111-4895-bb89-b93cc54faa9d)

**Comment by mikemcalister** [comment]
This is a great suggestion, Peter! I'll make this fix to a few of the pattern boxes. I'm going on parental leave soon, so I'm not sure I'll be able to sneak it in before then, but we'll get it in there!

**Comment by pmmueller** [comment]
There's no hurry. Your parental leave is definitely more important 🍀

**Comment by mikemcalister** [comment]
This fix has been implemented in the latest versions of the theme.
