### ISSUE TITLE
No Ollie dashboard in v09

### ISSUE THREAD

**Issue by dixplay** [OllieWP/ollie#96]
**The bug**
Hi, I tried installing Ollie today on a new WordPress website in its latest version and I don't have the popup and access to the Ollie dashboard.
So I installed v04 because I checked a past issue here and it works on v04, but not on v09.

**To Reproduce**
Creating a new WordPress website.
Going to add new theme.
Search for Ollie theme.
Install and activate it.

**Desktop**
 - Browser: Chrome, Firefox.

**Comment by nicolasmesser** [comment]
Did you install the theme from WP.org through the dashboard? Then you might already gotten the latest release that doesn't include the onboarding anymore.

Read more on the release and changes at [https://github.com/OllieWP/ollie/releases/tag/1.0.9](https://github.com/OllieWP/ollie/releases/tag/1.0.9)

**Comment by dixplay** [comment]
Oooooh I didn't know about that. Thank you!
