### ISSUE TITLE
ollie setup wizard

### ISSUE THREAD

**Issue by pikabon63** [OllieWP/ollie#99]
Hello, 
after installing ollie theme and activated it , i don't see Ollie setup wizard
I don't have the Ollie setup wizard by going to Appearance → Ollie → Theme Setup, or by following the pop-up upon theme activation.
Thanks for your assistance
Best regards

**Comment by nicolasmesser** [comment]
This issue has been opened many times - it's not a bug ... the setup wizard was removed from the main theme. See issue [](https://github.com/OllieWP/ollie/issues/98)

**Comment by pikabon63** [comment]
ok thanks for your answer
i've read issue #98. And i'll wait plugin's solution
best regards
